### ISSUE TITLE
Error On Create:  Binding to null instances is not allowed

### ISSUE THREAD

**Issue by austencollins** [awslabs/aws-apigateway-swagger-importer#1]
I'm new to the Java world, so forgive me if this is a simple issue.  But, I'm running into the following error when I try to create an API from my swagger.json:

```
    $ ./aws-api-import.sh --create ./swagger.json
    2015-07-21 11:59:09,719 ERROR - Error importing API from Swagger
    com.google.inject.CreationException: Unable to create injector, see the following errors:

    1) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
      at com.amazonaws.service.apigateway.importer.config.ApiImporterModule.configure(ApiImporterModule.java:44)

    1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:91)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:62)
```

**Comment by neoecos** [comment]
Exactly the same error here, does it supports swagger 2.0 ?

**Comment by rpgreen** [comment]
Swagger 2.0 is supported. Do you have the aws cli installed and configured via 'aws configure'?

**Comment by rpgreen** [comment]
It should now fallback to a default region if the region is not configured by the CLI. Let me know if you have any other issues.

**Comment by austencollins** [comment]
Yep, for the record I hadn't configured the aws-cli.  New update + configuring the aws-cli solved this issue.

Thanks Ryan

**Comment by neoecos** [comment]
Yes, I had configured aws cli with multiple profiles, and a default profile working.
