### ISSUE TITLE
BadRequestException: Invalid model specified (support Swagger models)

### ISSUE THREAD

**Issue by jblack10101** [awslabs/aws-apigateway-swagger-importer#10]
After updating the swagger dependency to be 

```
<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-core</artifactId>
    <version>1.5.0</version>
</dependency>
```

To get around this issue:

```
com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["hasAvailableEpisode"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Show"])
reading from swagger.json
```

I'm now getting this error:

```
2015-07-31 17:38:26,085 INFO - Generated json-schema for model RokuEpisodes: {"type":"object","properties":{"rokuEpisodes":{"type":"array","items":{"$ref":"#/definitions/RokuEpisode"}}},"xml":{"name":"episodes"},"definitions":{"RokuEpisode":{"type":"object","properties":{"tmsId":{"type":"string"},"title":{"type":"string"},"videos":{"$ref":"#/definitions/RokuVideos"}},"xml":{"name":"episode"}},"RokuOption":{"type":"object","properties":{"price":{"type":"string"},"currency":{"type":"string"},"quality":{"type":"string","enum":["SD","HD","HD_PLUS"]},"license":{"type":"string","enum":["FREE","PURCHASE","RENTAL","SUBSCRIPTION"]}},"xml":{"name":"option"}},"RokuViewOptions":{"type":"object","properties":{"options":{"type":"array","items":{"$ref":"#/definitions/RokuOption"}}},"xml":{"name":"viewOptions"}},"RokuVideo":{"type":"object","properties":{"region":{"type":"string"},"playId":{"type":"string"},"viewOptions":{"$ref":"#/definitions/RokuViewOptions"}},"xml":{"name":"video"}},"RokuVideos":{"type":"object","properties":{"videos":{"type":"array","items":{"$ref":"#/definitions/RokuVideo"}}},"xml":{"name":"videos"}}}}
2015-07-31 17:38:26,161 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified, Invalid model schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 79d02c64-37cc-11e5-b6c0-b562a252dc57)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
        at com.sun.proxy.$Proxy28.createModel(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModel(ApiGatewaySdkSwaggerApiImporter.java:167)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModel(ApiGatewaySdkSwaggerApiImporter.java:280)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModels(ApiGatewaySdkSwaggerApiImporter.java:273)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:89)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

Have any ideas about what could be going wrong?

My swagger.json was generated by using 'io.swagger:swagger-jersey-jaxrs:1.5.0'.

**Comment by rpgreen** [comment]
API Gateway validates models against the json-schema spec and is somewhat stricter than what Swagger accepts. Please ensure all referenced models are included in the "definitions" section. If you want to send your Swagger file I could take a look.

**Comment by jblack10101** [comment]
Yea, swagger is producing invalid JSON for us according to the json-schema draft-04 spec.  In the definitions section, it generated an errant 'xml' property:

```
"RokuEpisodes": {
    "type": "object",
    "properties": {
        "rokuEpisodes": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/RokuEpisode"
            }
        }
    },
    "xml": {
        "name": "episodes"
    }
},
```

Created github issue https://github.com/swagger-api/swagger.io/issues/28 with them.  Thanks for the suggestion.

**Comment by jblack10101** [comment]
So... it looks like Swagger is actually using a json-schema extension for that xml attribute, which should be valid: https://github.com/swagger-api/swagger.io/issues/28.  Would it be possible for the AWS API gateway schema validation to include this (and potentially other) extensions?

**Comment by rpgreen** [comment]
The comment in the other issue is correct. Swagger does use an "extended subset" of json-schema rather than strict json-schema. We will add support for this to our backlog, but for now we recommend sticking to json-schema compliant models if possible. I will leave this issue open for voting purposes.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
