### ISSUE TITLE
Import failing due to ResponseParameter mapping

### ISSUE THREAD

**Issue by pcutz** [awslabs/aws-apigateway-swagger-importer#104]
Hello,

I'm trying to do API gateway mapping of response headers, however I get the following error:

```
2015-12-01 15:07:20,168 INFO - Creating integration with type HTTP
2015-12-01 15:07:20,314 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping identifier specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 3a7afc56-9867-11e5-a6b6-0b5edfa99d75)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1249)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:870)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:574)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy37.putIntegrationResponse(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createIntegrationResponses$6(ApiGatewaySdkSwaggerApiImporter.java:279)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$14/15364204.accept(Unknown Source)
    at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:268)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:261)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:234)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:173)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$6/9903979.accept(Unknown Source)
    at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:172)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:164)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:154)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:144)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2015-12-01 15:07:20,314 INFO - Deleting API oy4uu5noxe
2015-12-01 15:07:21,235 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping identifier specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 3a7afc56-9867-11e5-a6b6-0b5edfa99d75)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1249)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:870)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:574)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy37.putIntegrationResponse(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createIntegrationResponses$6(ApiGatewaySdkSwaggerApiImporter.java:279)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$14/15364204.accept(Unknown Source)
    at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:268)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:261)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:234)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:173)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$6/9903979.accept(Unknown Source)
    at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:172)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:164)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:154)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:144)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

My AWS integration is:

``` json
"x-amazon-apigateway-integration": {
    "type": "http",
    "uri": "http://httpservice.com/jobs/{jobIdServlet}/requests/{requestIdServlet}/retrievefile",
    "httpMethod": "GET",
    "requestParameters": {
        "integration.request.path.jobIdServlet": "method.request.path.jobId",
        "integration.request.path.requestIdServlet": "method.request.path.requestId",
        "integration.request.header.Authorization": "method.request.header.Authorization"
    },
    "responses": {
        "default": {
            "statusCode": "200",
            "responseParameters": {
                "method.response.header.Content-Disposition": "integration.response.header.Content-Disposition",
                "method.response.header.Content-Type": "integration.response.header.Content-Type"
            }
        },
        "4\\d{2}.*": {
            "statusCode": "400"
        },
        "5\\d{2}.*": {
            "statusCode": "500"
        }
    }
}

```

I also tried it using the response parameters listed in the README.md file, but the error is the same.

for example: 

```
           "responseParameters" : {
               "method.response.header.test-method-response-header" : "'static value'"
           },
```

Is response parameter mapping currently supported by the API Gateway importer tool?

Thanks,
Patrick

**Comment by rpgreen** [comment]
It is supported. Are you able to get request parameters working? I'd
recommend adding things one at a time until you can identify the parameter
causing issues.

On Tuesday, 1 December 2015, pcutz notifications@github.com wrote:

> Hello,
> 
> I'm trying to do API gateway mapping of response headers, however I get
> the following error:
> 
> 2015-12-01 15:07:20,168 INFO - Creating integration with type HTTP
> 2015-12-01 15:07:20,314 ERROR - Error creating API, rolling back
> com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping identifier specified](Service: null; Status Code: 400; Error Code: null; Request ID: 3a7afc56-9867-11e5-a6b6-0b5edfa99d75)
>     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1249)
>     at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:870)
>     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:574)
>     at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
>     at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
>     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
>     at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
>     at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
>     at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
>     at com.sun.proxy.$Proxy37.putIntegrationResponse(Unknown Source)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createIntegrationResponses$6(ApiGatewaySdkSwaggerApiImporter.java:279)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$14/15364204.accept(Unknown Source)
>     at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:268)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:261)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:234)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:173)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$6/9903979.accept(Unknown Source)
>     at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:172)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:164)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
>     at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:154)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:144)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
> 2015-12-01 15:07:20,314 INFO - Deleting API oy4uu5noxe
> 2015-12-01 15:07:21,235 ERROR - Error importing API definition
> com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping identifier specified](Service: null; Status Code: 400; Error Code: null; Request ID: 3a7afc56-9867-11e5-a6b6-0b5edfa99d75)
>     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1249)
>     at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:870)
>     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:574)
>     at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
>     at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
>     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
>     at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
>     at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
>     at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
>     at com.sun.proxy.$Proxy37.putIntegrationResponse(Unknown Source)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createIntegrationResponses$6(ApiGatewaySdkSwaggerApiImporter.java:279)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$14/15364204.accept(Unknown Source)
>     at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:268)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:261)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:234)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:173)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$6/9903979.accept(Unknown Source)
>     at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:172)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:164)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
>     at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:154)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:144)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
> 
> My AWS integration is:
> 
> "x-amazon-apigateway-integration": {
>     "type": "http",
>     "uri": "http://httpservice.com/jobs/{jobIdServlet}/requests/{requestIdServlet}/retrievefile",
>     "httpMethod": "GET",
>     "requestParameters": {
>         "integration.request.path.jobIdServlet": "method.request.path.jobId",
>         "integration.request.path.requestIdServlet": "method.request.path.requestId",
>         "integration.request.header.Authorization": "method.request.header.Authorization"
>     },
>     "responses": {
>         "default": {
>             "statusCode": "200",
>             "responseParameters": {
>                 "method.response.header.Content-Disposition": "integration.response.header.Content-Disposition",
>                 "method.response.header.Content-Type": "integration.response.header.Content-Type"
>             }
>         },
>         "4\d{2}._": {
>             "statusCode": "400"
>         },
>         "5\d{2}._": {
>             "statusCode": "500"
>         }
>     }
> }
> 
> I also tried it using the response parameters listed in the README.md
> file, but the error is the same.
> 
> for example:
> 
> ```
>        "responseParameters" : {
>            "method.response.header.test-method-response-header" : "'static value'"
>        },
> ```
> 
> Is response parameter mapping currently supported by the API Gateway
> importer tool?
> 
> Thanks,
> Patrick
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/104.

##

**Comment by pcutz** [comment]
Yes, the request parameters are working.
The only difference between it working, and failing is the addition of responseParameters

Thanks,
Patrick

**Comment by rpgreen** [comment]
Do you have those parameters defined on your Swagger operation? Please post your full swagger definition if possible

**Comment by pcutz** [comment]
That may be the issue. 
I do not have them defined, I am not aware how to define response headers in swagger.

The method that I have is to download a file from another http service that we have.
Using output passthrough with API gateway makes this possible.
The header of the response will pass the filename and file type.

I have configured this manually in API Gateway, and confirmed that it's working.
However the import tool is failing to get this to work.

The swagger definition I'm using is:

``` json
"/jobs/{jobId}/requests/{requestId}/retrievefile": {
    "get": {
        "summary": "Retrieve the target content for translation request(s) as a file.",
        "description": "Retrieve the target content for translation request(s) as a file.",
        "tags": [
            "File"
        ],
        "consumes": [
            "application/octet-stream"
        ],
        "parameters": [
            {
                "name": "Authorization",
                "in": "header",
                "description": "Oauth2 token",
                "required": true,
                "type": "string"
            },
            {
                "name": "jobId",
                "in": "path",
                "description": "The ID of the job.",
                "required": true,
                "type": "string"
            },
            {
                "name": "requestId",
                "in": "path",
                "description": "The ID of the translation request.",
                "required": true,
                "type": "string"
            }
        ],
        "security": [
            {
                "basicsecurity": [
                    "all"
                ]
            }
        ],
        "responses": {
            "200": {
                "description": "Target content.",
                "schema": {
                    "type": "file"
                }
            },
            "400": {
                "description": "Client error",
                "schema": {
                    "$ref": "#/definitions/Error"
                }
            },
            "500": {
                "description": "Server error",
                "schema": {
                    "$ref": "#/definitions/Error"
                }
            }
        },
        "x-amazon-apigateway-auth": {
            "type": "none"
        },
        "x-amazon-apigateway-integration": {
            "type": "http",
            "uri": "http://httpservice.com/jobs/{jobIdServlet}/requests/{requestIdServlet}/retrievefile",
            "httpMethod": "GET",
            "requestParameters": {
                "integration.request.path.jobIdServlet": "method.request.path.jobId",
                "integration.request.path.requestIdServlet": "method.request.path.requestId",
                "integration.request.header.Authorization": "method.request.header.Authorization"
            },
            "responses": {
                "default": {
                    "statusCode": "200",
                    "responseParameters": {
                        "method.response.header.Content-Disposition": "integration.response.header.Content-Disposition",
                        "method.response.header.Content-Type": "integration.response.header.Content-Type"
                    }
                },
                "4\\d{2}.*": {
                    "statusCode": "400"
                },
                "5\\d{2}.*": {
                    "statusCode": "500"
                }
            }
        }
    }
},
```

Thanks for your help,
Patrick

**Comment by rpgreen** [comment]
Specify headers like this:

```
"responses": {
      "200": {
                "description": "Target content.",
                "schema": {
                    "type": "file"
                },
                "headers" : {
                            "Content-Disposition" : {
                                "type" : "string"
                            }
                        }
                    },
```

More examples at https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/swagger/apigateway.json
