### ISSUE TITLE
HTTP Proxy Integration with RAML Config

### ISSUE THREAD

**Issue by spencerfdavis** [awslabs/aws-apigateway-swagger-importer#109]
I've been able to successfully configure an integration to call a lambda function.  I keep getting an error though when I try and setup an integration endpoint that calls an HTTP Proxy.  I used an example in the tests folder but cannot seem to get it working.

My example...

``` json
{
    "/api/v1/users/search/email": {
        "get": {
            "integration" : {
                "type" : "http",
                "uri": "http://www.google.com",
                "httpMethod": "GET",
                "requestTemplates" : {
                    "application/json" : ""
                },
                "responses" : {
                    "default" : {
                        "statusCode" : "200",
                        "responseTemplates" : {
                            "application/json" : ""
                        }
                    }
                }
            }
        }
    }
}
```

Error I get

``` bash
2015-12-02 10:06:51,458 INFO - Creating integration with type HTTP
2015-12-02 10:06:54,258 ERROR - Error creating API, rolling back
com.amazonaws.AmazonServiceException:  (Service: null; Status Code: 500; Error Code: null; Request ID: 1627c293-9917-11e5-9a05-3738b38200c6)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy30.putIntegration(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createIntegration(ApiGatewaySdkRamlApiImporter.java:303)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createMethod(ApiGatewaySdkRamlApiImporter.java:256)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createMethods(ApiGatewaySdkRamlApiImporter.java:180)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createResources(ApiGatewaySdkRamlApiImporter.java:149)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createResources(ApiGatewaySdkRamlApiImporter.java:150)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createResources(ApiGatewaySdkRamlApiImporter.java:150)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createApi(ApiGatewaySdkRamlApiImporter.java:83)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.importApi(ApiGatewayRamlFileImporter.java:49)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:121)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

Anyone able to successfully get an HTTP Proxy integration working with RAML?

**Comment by rpgreen** [comment]
Does this work?

```
{
    "/api/v1/users/search/email": {
        "get": {
            "integration" : {
                "type" : "http",
                "uri": "http://www.google.com",
                "httpMethod": "GET",
                "requestTemplates" : {
                },
                "responses" : {
                    "default" : {
                        "statusCode" : "200",
                        "responseTemplates" : {
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by spencerfdavis** [comment]
@rpgreen That did it.  Thanks :+1:
