### ISSUE TITLE
NullPointerException when model Exists

### ISSUE THREAD

**Issue by jjmartin** [awslabs/aws-apigateway-swagger-importer#112]
```
2015-12-07 08:56:13,625 ERROR - Error importing API definition
java.lang.NullPointerException
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.getApiName(ApiGatewaySdkSwaggerApiImporter.java:92)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:60)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

This happens with i have my model defined... 

```
...
"responses": {
                    "200": {
                        "description": "invoice details",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/invoiceDetail"
                            }
                        }
                    },
...
 "definitions": {
        "invoiceDetail": {
            "type": "object",
            "required": null,
            "properties": {
                "customercommonid": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "availabilityzone": {
                    "type": "string"
                },
                "quantity": {
                    "type": "float"
                },
                "usagetype": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "pricetype": {
                    "type": "string"
                },
                "startdate": {
                    "type": "string",
                    "format": "date-time"
                },
                "enddate": {
                    "type": "string",
                    "format": "date-time"
                },
                "isreservedinstance": {
                    "type": "bool"
                },
                "resourceid": {
                    "type": "string"
                },
                "price": {
                    "type": "float"
                }
            }
        },
...
```

when i remove the definition:

```
...
"200": {
                        "description": "invoice details",
                        "schema": {
                            "type": "array",
                            "items": {

                            }
                        }
                    },
...
 "definitions": {
//invoiceDetails was here
        "errorModel": {
...
```

the api successfully creates.

**Comment by jackrk** [comment]
That stack trace doesn't make a lot of sense to me considering the swagger def you've posted. Are you sure that's an accurate stack trace? 

The stack trace would indicate that the API name can't be parsed out of the swagger def, so maybe the brackets aren't closed properly? 

https://github.com/awslabs/aws-apigateway-importer/blob/master/src/com/amazonaws/service/apigateway/importer/impl/sdk/ApiGatewaySdkSwaggerApiImporter.java#L91

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
