### ISSUE TITLE
RAML 1.0 support?

### ISSUE THREAD

**Issue by Shockolate** [awslabs/aws-apigateway-swagger-importer#116]
I am receiving errors from SnakeYaml whenever it finds a RAML 1.0 feature. Shown below is the error I get from using the "uses" keyword. I tried removing it from my RAML spec, but then it failed on the "types" keyword. Sooo my question:

Is RAML 1.0 supported?

Stefano Buliani told me in an email that it is, but I'm skeptical with this error.

P.S. I created my RAML with API Workbench but I doubt that could affect it.

``` Shell
2015-12-08 13:48:20,980 INFO - Using API Gateway endpoint https://apigateway.us-east-1.amazonaws.com
2015-12-08 13:48:22,111 INFO - Attempting to create API from RAML definition. RAML file: ../API_Workbench/ScanEvents/api.raml
2015-12-08 13:48:22,187 ERROR - Error importing API definition
java.lang.RuntimeException: Builder not found for <NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=uses
)>; valueNode=<org.yaml.snakeyaml.nodes.MappingNode (tag=tag:yaml.org,2002:map, values={ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.
org,2002:str, value=ScanEventsModel)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=ScanEvent
sModel)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=!include, value=schemas/ScanEvents.raml)>> }{ key=<org.yaml.snakeyaml.nodes.Scalar
Node (tag=tag:yaml.org,2002:str, value=rTypes)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value
=rTypes)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=!include, value=resourceTypes/CollectionAndMember.raml)>> })>>
        at org.raml.parser.builder.DefaultTupleBuilder.getBuilderForTuple(DefaultTupleBuilder.java:68)
        at org.raml.parser.visitor.YamlDocumentBuilder.onTupleStart(YamlDocumentBuilder.java:272)
        at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:145)
        at org.raml.parser.visitor.NodeVisitor.visitDocument(NodeVisitor.java:209)
        at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:90)
        at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:102)
        at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:78)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.parse(ApiGatewayRamlFileImporter.java:73)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.importApi(ApiGatewayRamlFileImporter.java:47)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importRaml(ApiImporterMain.java:171)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:141)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by rpgreen** [comment]
@blakeembrey - RAML 1.0 is supported right?

**Comment by blakeembrey** [comment]
RAML 1.0 is not supported yet, we're working on building a RAML 1.0 parser in Java right now.

**Comment by FingerLiu** [comment]
@blakeembrey since 10 month past, is RAML 1.0 supported now?
