### ISSUE TITLE
Updating path params

### ISSUE THREAD

**Issue by etzlers** [awslabs/aws-apigateway-swagger-importer#118]
I have an existing path definition in AWS API Gateway as follows:

``` yaml
  /equipment/{equipmentKey}:
    get:
      summary: Equipment
      description: >
        The Equipment endpoint returns a Equipment for the specified id.
      parameters:
        - name: equipmentKey
          in: path
          description: Unique identifier for the Equipment.
          type: string
          required: true
          format: string
      tags:
        - Equipment
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:GetEquipment/invocations
        credentials: arn:aws:iam::XXXXXXXXXXXX:role/lambda_gateway_execution
        httpMethod: POST
        requestTemplates:
          application/json: |
            "${input.params('equipmentKey')}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
          Error 404.*:
            statusCode: "404"
          Error:.*:
            statusCode: "500"
      responses:
        '200':
          description: A single Equipment.
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Equipment'
        '404':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
```

When I try to run --update and --deploy with the definition changed to be as follows (changed the path param from equipmentKey to id and from a string to integer) I receive the error following the changed path definition below.

``` yaml
  /equipment/{id}:
    get:
      summary: Equipment
      description: >
        The Equipment endpoint returns a Equipment for the specified id.
      parameters:
        - name: id
          in: path
          description: Unique identifier for the Equipment.
          type: integer
          required: true
          format: int32
      tags:
        - Equipment
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:GetEquipment/invocations
        credentials: arn:aws:iam::XXXXXXXXXXXX:role/lambda_gateway_execution
        httpMethod: POST
        requestTemplates:
          application/json: |
            "${input.params('id')}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
          Error 404.*:
            statusCode: "404"
          Error:.*:
            statusCode: "500"
      responses:
        '200':
          description: A single Equipment.
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Equipment'
        '404':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
```

Error:

```
2015-12-08 15:24:41,450 INFO - Creating resource '{id}' on XXXXXX
2015-12-08 15:24:41,597 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Resource with id 'null' has more than o
ne variable component as a direct child: [{equipmentKey}, {id}] (Service: null; Status Code: 400; Er
ror Code: null; Request ID: b6cc47fc-9de9-11e5-8a67-63e272a659cc)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler
.java:117)
        at com.sun.proxy.$Proxy32.createResource(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createResourc
e(ApiGatewaySdkApiImporter.java:233)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Resources(ApiGatewaySdkSwaggerApiImporter.java:157)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.update
Resources(ApiGatewaySdkSwaggerApiImporter.java:374)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.update
Api(ApiGatewaySdkSwaggerApiImporter.java:83)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(Ap
iGatewaySwaggerFileImporter.java:58)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:14
3)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

I would expect this change to update without issue but is there a reason this shouldn't work?

**Comment by rpgreen** [comment]
Looks like a bug. To get you unblocked, just remove the method from your Swagger, update, and then add the new one back and update again

**Comment by etzlers** [comment]
Thank you, is this a bug with the importer or with API Gateway itself?

**Comment by kahouieong** [comment]
@etzlers 
It looks like a bug with the importer. As workaround, you can follow what @rpgreen mentioned. We will prioritize to fix this issue.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan

**Comment by Gaurav-Deshkar** [comment]
Hey I am getting same error, looks like not yet fixed.

```
   "/travelPlan/{travelNumber}/{windowStartTime}": {
      "get": {
        "tags": [
          "travel-plan-controller"
        ],
        "summary": "gettravelPlanBytravelNumberAndDate",
        "operationId": "gettravelPlanBytravelNumberAndDateUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "travelNumber",
            "in": "path",
            "description": "travelNumber",
            "required": true,
            "type": "string"
          },
          {
            "name": "windowStartTime",
            "in": "path",
            "description": "windowStartTime",
            "required": true,
            "type": "ref"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/travelPlan"
              }
            }
          }
        }
      }
    },
    "/travelPlan/{travelPlanID}": {
      "get": {
        "tags": [
          "travel-plan-controller"
        ],
        "summary": "gettravelPlanBytravelPlanID",
        "operationId": "gettravelPlanBytravelPlanIDUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "travelPlanID",
            "in": "path",
            "description": "travelPlanID",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/travelPlan"
            }
          }
        }
      }
    },
```

```
 2016-04-13 14:17:55,009 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Resource with id 'null' has more than one variable component as a direct child: [{travelNumber}, {travelPlanID}] (Service: null; Status Code: 400; Error Code: null; Request ID: 696adb1a-0154-11e6-9a83-2f6b8d40333a)
  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
  at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
  at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
  at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
  at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
```

**Comment by jt0** [comment]
This case is actually different.  API Gateway's built-in importer creates intermediate resources for you (even if they don't have methods associated with them) since every resource needs to have a parent.  That means that this Swagger file would result in resources with the following paths if the import was successful:

/
/travelPlan
/travelPlan/{travelPlanID}
/travelPlan/{travelNumber}
/travelPlan/{travelNumber}/{windowStartTime}

In this case, /travelPlan/{travelPlanID} and /travelPlan/{travelNumber} are ambiguous because API Gateway doesn't know which one you meant if an operation was performed on it.  A (good) argument could be made that if the methods don't also conflict, there isn't any ambiguity and so should be allowed.  I will add this for consideration to API Gateway's backlog.

In the meantime, a workaround would be to rename the variable to something like {travelPlanIDorNumber} and use that in both Swagger paths.
