### ISSUE TITLE
StringIndexOutOfBoundsException if the RAML baseUri does not have a trailing slash

### ISSUE THREAD

**Issue by aviflax** [awslabs/aws-apigateway-swagger-importer#120]
For example, if my `baseUri` has the value `https://my.host.name` then the tool will print this output:

```
2015-12-09 15:08:13,829 ERROR - Error importing API definition
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1927)
    at org.raml.model.Raml.getBasePath(Raml.java:141)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createApi(ApiGatewaySdkRamlApiImporter.java:83)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.importApi(ApiGatewayRamlFileImporter.java:49)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importRaml(ApiImporterMain.java:171)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:141)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

I think it’s fine to require that `baseUri` have a trailing slash; it would just be nice if the error message made clear that that’s the problem.

Tool was built with fd836aa86b54e502fe55ffbdc441f57b4ed316ce and I’m using the überjar.

**Comment by jackrk** [comment]
This should be a quick fix, and it seems like a bug to me. I'll notify the lead dev, or you could submit a pull request if you'd like. 

Thanks for bringing this to our attention.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
