### ISSUE TITLE
Invalid model schema specified - JSONschema4 + RAML

### ISSUE THREAD

**Issue by Shockolate** [awslabs/aws-apigateway-swagger-importer#126]
Not really sure where my json-schema is wrong. I'm using [this website](http://www.jsonschemavalidator.net/) to validate my schema.

I am willing to send any files asked for

```
$ aws-api-import.sh -c ../API_Workbench/ScanEvents08/api.raml --region us-east-1
./aws-api-import.sh: line 2: readlink: command not found
2015-12-17 13:58:41,310 INFO - Using API Gateway endpoint https://apigateway.us-east-1.amazonaws.com
2015-12-17 13:58:42,429 INFO - Attempting to create API from RAML definition. RAML file: ../API_Workbench/ScanEvents08/api.raml
2015-12-17 13:58:42,558 INFO - Creating API with name Scan Tracker
2015-12-17 13:58:42,868 INFO - Removing default model Error
2015-12-17 13:58:42,912 INFO - Removing default model Empty
2015-12-17 13:58:43,048 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model
schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 3144d91a-a4f0-11e5-a90c-e303219c2223)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
        at com.sun.proxy.$Proxy24.createModel(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createModel(ApiGatewaySdkApiImporter.java:139)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createModel(ApiGatewaySdkRamlApiImporter.java:141)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createModels(ApiGatewaySdkRamlApiImporter.java:122)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createApi(ApiGatewaySdkRamlApiImporter.java:82)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.importApi(ApiGatewayRamlFileImporter.java:49)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importRaml(ApiImporterMain.java:171)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:141)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2015-12-17 13:58:43,062 INFO - Deleting API vn4o0rvck4
2015-12-17 13:58:43,604 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model
schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 3144d91a-a4f0-11e5-a90c-e303219c2223)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
        at com.sun.proxy.$Proxy24.createModel(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createModel(ApiGatewaySdkApiImporter.java:139)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createModel(ApiGatewaySdkRamlApiImporter.java:141)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createModels(ApiGatewaySdkRamlApiImporter.java:122)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createApi(ApiGatewaySdkRamlApiImporter.java:82)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.importApi(ApiGatewayRamlFileImporter.java:49)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importRaml(ApiImporterMain.java:171)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:141)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by jackrk** [comment]
We'd just like to see the JSON Schema Model def if possible. I would expect the behavior of the service to match the test tool you linked to, provided that the test tool is not buggy. 

Jack

**Comment by Shockolate** [comment]
I believe the error is with the first schema that I have posted.

1

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A collection of ScanEvents",
  "type": "array",
  "title": "OutgoingScanEvents",
  "items": [
    {  "$ref": "#/definitions/OutgoingScanEvent" }
  ],

  "definitions": {
    "OutgoingScanEvent": {
      "type": "object",
      "properties": {
        "Context": {
          "type": "string",
          "minLength": 1
        },
        "SatellitePrinterId": {
          "type": "string",
          "minLength": 1
        },
        "ScanDateTime": {
          "type": "string",
          "minLength": 1
        },
        "ScannedText": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "Context",
        "SatellitePrinterId",
        "ScanDateTime",
        "ScannedText"
      ]}
  }
}
```

2

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "The Scan Event data to be sent to the Primary Plant",
  "type": "object",
  "properties": {
    "Context": {
      "type": "string",
      "minLength": 1
    },
    "SatellitePrinterId": {
      "type": "string",
      "minLength": 1
    },
    "ScanDateTime": {
      "type": "string",
      "minLength": 1
    },
    "ScannedText": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "Context",
    "SatellitePrinterId",
    "ScanDateTime",
    "ScannedText"
  ]
}
```

3

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "The ScanEvent that is coming from the Satellite Printer",
  "type": "object",
  "properties": {
    "Context": {
      "type": "string",
      "minLength": 1
    },
    "SatellitePrinterId": {
      "type": "string",
      "minLength": 1
    },
    "ScannedText": {
      "type": "string",
      "minLength": 1
    },
    "PrimaryId": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "Context",
    "SatellitePrinterId",
    "ScannedText",
    "PrimaryId"
  ]
}
```

4

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "error",
  "description": "Error message that is supplied with an HTTP Error Status Code.",
  "type": "object",
  "properties": {
    "error": {
      "description": "The error message.",
      "type": "string",
      "minLength": 1
    },
    "code": {
      "type": "number",
      "description": "The HTTP Status Code."
    }
  },
  "required": [
    "error",
    "code"
  ]
}
```

**Comment by jackrk** [comment]
Did you copy the first model correctly? When I paste that into the JSON Schema validator link that you originally provided, it says 1 error found "Invalid type. Expected Array but got Object."

**Comment by Shockolate** [comment]
Jackrk,
That error means the validator was able to parse the schema, but the input JSON is not valid for the schema.

**Comment by jackrk** [comment]
Ah my mistake you're right. I'm trying to log dive now to find the request you have pasted in your original post.

**Comment by jackrk** [comment]
Alright my apologies, I have the answer. We have a bug in our validator right now that doesn't handle the description field right. So if you remove the description, it will work (I tested manually in the console adding a Model). 

Also, it was recommended to me that you change the items from:

``` json
"items": [
  {  "$ref": "#/definitions/OutgoingScanEvent" }
],
```

to 

``` json
"items": {  
  "$ref": "#/definitions/OutgoingScanEvent" 
}
```

**Comment by Shockolate** [comment]
Hmmm, I remember seeing that in another issue but I thought it was resolved...
My apologies for not picking up on that and posting a duplicate issue (aka wasting your time).

How can I dive into the logs myself with the request ID?

Thank you so much for your help, Jackrk, I really appreciate it!
