### ISSUE TITLE
Cannot deploy basic configuration

### ISSUE THREAD

**Issue by danhart** [awslabs/aws-apigateway-swagger-importer#129]
I'm probably missing something obvious here. Here is my swagger configuration:

``` yaml

---
swagger: "2.0"
info:
  title: ExchangeStats
paths:
  /test:
    get:
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:<account-id>:function:broadband-exchange-stats/invocations
        httpMethod: POST
        requestTemplates:
          application/json: "Empty"
        responses:
          "default":
            statusCode: "200"
      responses:
        200:
          description: "ok"
```

I can successfully create the API:

```
./aws-api-import.sh --create exchange-stats.yaml
2015-12-21 12:28:18,054 INFO - Using API Gateway endpoint https://apigateway.eu-west-1.amazonaws.com
2015-12-21 12:28:19,042 INFO - Attempting to create API from Swagger definition. Swagger file: exchange-stats.yaml
reading from exchange-stats.yaml
2015-12-21 12:28:19,112 INFO - Parsed Swagger with 1 paths
2015-12-21 12:28:19,112 INFO - Creating API with name ExchangeStats
2015-12-21 12:28:19,345 INFO - Removing default model Error
2015-12-21 12:28:19,388 INFO - Removing default model Empty
2015-12-21 12:28:19,467 INFO - Creating resource 'test' on ulmh3wp3cb
2015-12-21 12:28:19,655 INFO - Creating method response for api 3kyzu48l7j and method GET and status 200
2015-12-21 12:28:19,752 INFO - Creating integration with type AWS
2015-12-21 12:28:19,862 INFO - Creating method for api id 3kyzu48l7j and resource id 07w5kb with method get
```

But not deploy it:

```
./aws-api-import.sh --update 3kyzu48l7j --deploy prod exchange-stats.yaml
2015-12-21 12:28:28,541 INFO - Using API Gateway endpoint https://apigateway.eu-west-1.amazonaws.com
2015-12-21 12:28:29,413 INFO - Attempting to update API from Swagger definition. API identifier: 3kyzu48l7j Swagger file: exchange-stats.yaml
reading from exchange-stats.yaml
2015-12-21 12:28:29,483 INFO - Parsed Swagger with 1 paths
2015-12-21 12:28:29,678 INFO - Updating method for api id 3kyzu48l7j and resource 07w5kb and method get
2015-12-21 12:28:29,805 INFO - Creating method response for api 3kyzu48l7j and method GET and status 200
2015-12-21 12:28:29,936 INFO - Creating integration with type AWS
2015-12-21 12:28:30,057 INFO - Cleaning up removed methods
2015-12-21 12:28:30,132 INFO - Cleaning up removed resources
2015-12-21 12:28:30,172 ERROR - Error importing API definition
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:88)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:161)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

Possibly something to do with models that don't exist?

**Comment by danhart** [comment]
I added a definitions section and that seems to have fixed it.
