### ISSUE TITLE
Using multiple yaml files

### ISSUE THREAD

**Issue by koryshev** [awslabs/aws-apigateway-swagger-importer#131]
my Swagger API became too large and i want to split it into multiple files. 
Swagger spec says that you can reference on other remote and local yaml files via a $ref
Is it possible to use this feature with this importer? i tried [this](https://github.com/awslabs/aws-apigateway-importer/files/70920/swagger.zip) yaml file with references on local files but importing of new API failed, stacktrace

```
2015-12-23 18:13:54,630 INFO - Creating model for api id ivxadyb1rl with name TestModel
2015-12-23 18:13:54,785 ERROR - Error creating API, rolling back
java.lang.IllegalStateException: Invalid schema json was generatedJSON value is of type null, not a JSON Schema (expected an object)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.validate(SchemaTransformer.java:107)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.getFlattened(SchemaTransformer.java:89)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.flatten(SchemaTransformer.java:47)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.generateSchemaString(ApiGatewaySdkSwaggerApiImporter.java:328)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.generateSchema(ApiGatewaySdkSwaggerApiImporter.java:339)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModel(ApiGatewaySdkSwaggerApiImporter.java:112)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModels(ApiGatewaySdkSwaggerApiImporter.java:105)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:65)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2015-12-23 18:13:54,787 INFO - Deleting API ivxadyb1rl
```

p.s. I checked attached file with [SwaggerParser](https://github.com/swagger-api/swagger-parser) and it was successfully read.

**Comment by lorenzoaws** [comment]
This looks related to essentially the same issue reported with json swagger files : https://github.com/awslabs/aws-apigateway-importer/issues/117

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
