### ISSUE TITLE
Cannot import model with forward references

### ISSUE THREAD

**Issue by ifullgaz** [awslabs/aws-apigateway-swagger-importer#135]
I have a model definition with forward reference like so:

```
{
  "User": {
    "type": "object",
    "properties": {
      "objectId": {
        "type": "string"
      },
      "username": {
        "type": "string"
      },
      "profilePic": {
        "$ref": "#/definitions/File"
      },
      "createdAt": {
        "type": "integer"
      },
      "updatedAt": {
        "type": "integer"
      }
    }
  },
  "File": {
    "type": "object",
    "properties": {
      "objectId": {
        "type": "integer"
      },
      "owner": {
        "$ref": "#/definitions/User"
      },
      "mime": {
        "type": "string"
      },
      "options": {
        "type": "string"
      },
      "createdAt": {
        "type": "integer"
      },
      "updatedAt": {
        "type": "integer"
      }
    }
  }
}
```

The importer crashes with the following stack:

```
java.lang.StackOverflowError
    at java.util.HashMap.hash(HashMap.java:338)
    at java.util.LinkedHashMap.get(LinkedHashMap.java:440)
    at com.fasterxml.jackson.databind.node.ObjectNode.path(ObjectNode.java:107)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.findReferences(SchemaTransformer.java:137)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:52)
```

**Comment by kahouieong** [comment]
@ifullgaz 
This seems like a bug in the importer. Could you mind providing the whole swagger JSON file for further investigation?

**Comment by ifullgaz** [comment]
Sure, here it is. Please note that I masked my account id and replaced it with ACCOUNT_ID.
[TestImporter.zip](https://github.com/awslabs/aws-apigateway-importer/files/74491/TestImporter.zip)

**Comment by kahouieong** [comment]
@ifullgaz 
It looks like related to this pull request (https://github.com/awslabs/aws-apigateway-importer/pull/132/files). Can you try pulling this change to see if it works for you?

**Comment by ifullgaz** [comment]
I've just tried but it doesn't solve this particular problem.
The importer still fails with the following error:

```
Error creating API, rolling back
java.lang.StackOverflowError
    at java.util.HashMap.putVal(HashMap.java:628)
    at java.util.HashMap.put(HashMap.java:611)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.findReferences(SchemaTransformer.java:139)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.findReferences(SchemaTransformer.java:143)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.findReferences(SchemaTransformer.java:143)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:52)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
    at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
...
```

It looks like an infinite recursion or something similar.

**Comment by kahouieong** [comment]
@ifullgaz 
The importer will try to flatten your model definition from inline reference to nested object. I think the issue is you have circular references in your model definition.

**Comment by ifullgaz** [comment]
I understand but it's still a limitation, can it be fixed?

**Comment by kahouieong** [comment]
That is the limitation in AWS API Gateway management service. We are looking for a way to handle this case properly, but there is no way easy workaround currently. I apologize that.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
