### ISSUE TITLE
StackOverflow for particular swagger doc import

### ISSUE THREAD

**Issue by petemounce** [awslabs/aws-apigateway-swagger-importer#139]
I have a swagger document that contains an object, with a property named the same as another object definition - the importer then stackoverflows.

Snippet

``` yaml
  AreaStatistic:
    type: object
    properties:
      Area:
        $ref: '#/definitions/Area'
      Count:
        type: integer
      Revenue:
        type: number
        format: double
      AverageValuePerOrder:
        type: number
        format: double
  Area:
    type: object
    properties:
      Outcode:
        type: string
```

output

```
> java -jar tools/aws-apigateway-importer/aws-apigateway-importer-1.0.3-SNAPSHOT-jar-with-dependencies.jar --create .\apis\restaurantanalytics.swagger.yaml
2016-01-09 22:29:06,067 INFO - Using API Gateway endpoint https://apigateway.eu-west-1.amazonaws.com
2016-01-09 22:29:07,700 INFO - Attempting to create API from Swagger definition. Swagger file: .\apis\restaurantanalytics.swagger.yaml
reading from .\apis\restaurantanalytics.swagger.yaml
2016-01-09 22:29:07,825 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:07,841 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:07,872 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:07,919 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:07,966 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:07,997 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:08,044 WARN - no property from number, int32, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=nul
l, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=n
ull, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=int32}
2016-01-09 22:29:08,091 INFO - Parsed Swagger with 1 paths
2016-01-09 22:29:08,091 INFO - Creating API with name je-restaurantanalytics-qa13-uk
2016-01-09 22:29:08,403 INFO - Removing default model Empty
2016-01-09 22:29:08,559 INFO - Removing default model Error
2016-01-09 22:29:08,638 INFO - Creating model for api id cqk83475t9 with name OrderStatistics
2016-01-09 22:29:08,903 INFO - Generated json-schema for model OrderStatistics: {"type":"object","properties":{"Accepted":{"type":"object"},"Rejected":{"type":"object
"}},"definitions":{}}
2016-01-09 22:29:09,013 INFO - Creating model for api id cqk83475t9 with name LocationStatistic
2016-01-09 22:29:09,075 ERROR - Error creating API, rolling back
java.lang.StackOverflowError
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValue(ObjectNode.java:165)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValue(ObjectNode.java:169)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValue(ObjectNode.java:169)
        at com.fasterxml.jackson.databind.node.BaseJsonNode.findPath(BaseJsonNode.java:33)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.getSchema(SchemaTransformer.java:71)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:59)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)

............

        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
2016-01-09 22:29:09,434 INFO - Deleting API cqk83475t9
2016-01-09 22:29:09,810 ERROR - Error importing API definition
java.lang.StackOverflowError
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValue(ObjectNode.java:165)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValue(ObjectNode.java:169)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValue(ObjectNode.java:169)
        at com.fasterxml.jackson.databind.node.BaseJsonNode.findPath(BaseJsonNode.java:33)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.getSchema(SchemaTransformer.java:71)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:59)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)
        at com.amazonaws.service.apigateway.importer.impl.SchemaTransformer.buildSchemaReferenceMap(SchemaTransformer.java:64)

..............
```

**Comment by petemounce** [comment]
(While I'm here, I also don't understand the warnings. It would help if they referenced which object and property they were warning about?)

**Comment by rpgreen** [comment]
Thanks for reporting. Circular references are currently not supported. Tracking in https://github.com/awslabs/aws-apigateway-importer/issues/135
