### ISSUE TITLE
Example of basic swagger

### ISSUE THREAD

**Issue by picsoung** [awslabs/aws-apigateway-swagger-importer#14]
I am having issues deploying an existing swagger of mine 

```
./aws-api-import.sh --create ./swagger.json
2015-08-07 14:45:45,108 ERROR - /path/to/swagger.json
2015-08-07 14:45:45,109 INFO - Attempting to create API from Swagger definition. Swagger file:  /path/to/swagger.json
reading from  /path/to/swagger.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from /path/to/swagger.json
2015-08-07 14:45:45,127 ERROR - Error importing API from Swagger
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.getApiName(ApiGatewaySdkSwaggerApiImporter.java:236)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:84)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:102)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

Would you mind include a basic example of a working swagger spec, like the petstor API, to check if it's the error is on the way I wrote the swagger spec or on my config?

Thanks

**Comment by picsoung** [comment]
Found some in `/tst/resources`

Sorry about that
