### ISSUE TITLE
Assume role in profile is not supported?

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-apigateway-swagger-importer#146]
I have the following config

```
[default]
aws_access_key_id = ***
aws_secret_access_key = ***

[profile MyRole]
source_profile = default
role_arn = arn:aws:iam::************:role/MyRole
```

When i execute the following:

```
aws-api-import.sh --update ${AWS_API_ID} --deploy ${AWS_API_STAGE} swagger.yaml --region ${REGION} --profile MyRole
```

I receive the following error:

```
1) Error in custom provider, com.amazonaws.AmazonServiceException: User: arn:aws:iam::************:user/********** is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:eu-west-1::/ (Service: null; Status Code: 403; Error Code: null; Request ID: *******)
  at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:63)
  while locating com.amazonaws.services.apigateway.model.ApiGateway
    for field at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.apiGateway(ApiGatewaySdkApiImporter.java:43)
  while locating com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter
  while locating com.amazonaws.service.apigateway.importer.SwaggerApiImporter
    for parameter 1 at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.<init>(ApiGatewaySwaggerFileImporter.java:36)
  while locating com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
Caused by: com.amazonaws.AmazonServiceException: User: arn:aws:iam::************:user/********** is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:eu-west-1::/ (Service: null; Status Code: 403; Error Code: null; Request ID: *******)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1286)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.getHalResource(HalClient.java:210)
    at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:200)
    at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:92)
    at com.amazonaws.hal.HalService.getRootResource(HalService.java:128)
    at com.amazonaws.services.apigateway.AmazonApiGateway.getApiGateway(AmazonApiGateway.java:113)
    at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:299)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
    at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    ... 3 more
make: *** [update] Error 1
```

Should this work? Or is it something that needs to be added? 

We use the assume role feature to authorise federated users and execute tasks cross account, so we need this to be supported in order to use this importer....

**Comment by rpgreen** [comment]
This is supported but the assumed role will need appropriate permissions to manage the API

**Comment by Nr18** [comment]
Well i tested it with a Administrator role that has ALL access within the account and it still didn't work.

Please note that it isn't a instance role that i'm referring to but a IAM User that assumes a Role. (I just realised that i have MFA configured as well)

```
[default]
aws_access_key_id = ***
aws_secret_access_key = ***

[profile MyRole]
source_profile = default
role_arn = arn:aws:iam::************:role/MyRole
mfa_serial = arn:aws:iam::********:mfa/*****
```

I will test it with a user that won't require a MFA Token.

**Comment by Nr18** [comment]
Just tested it

```
aws-api-import.sh --update ${AWS_API_ID} --deploy ${AWS_API_STAGE} ${PWD}/AWS/API/swagger.yaml --profile MyRoleWithoutMFA --region ${REGION}
```

With the config:

```
[default]
aws_access_key_id = ***
aws_secret_access_key = ***

[profile MyRoleWithoutMFA]
source_profile = default
region = eu-west-1
role_arn = arn:aws:iam::************:role/MyRoleWithoutMFA
```

arn:aws:iam::************:role/MyRoleWithoutMFA has the policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

And the configured access key has the right to assume the role.

```
2016-01-18 22:58:43,462 INFO - Using API Gateway endpoint https://apigateway.eu-west-1.amazonaws.com
2016-01-18 22:58:46,013 ERROR - Error importing API definition
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
  at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:63)
  while locating com.amazonaws.services.apigateway.model.ApiGateway
    for field at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.apiGateway(ApiGatewaySdkApiImporter.java:43)
  while locating com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter
  while locating com.amazonaws.service.apigateway.importer.SwaggerApiImporter
    for parameter 1 at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.<init>(ApiGatewaySwaggerFileImporter.java:36)
  while locating com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
    at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:229)
    at com.amazonaws.hal.client.HalClient.getHalResource(HalClient.java:210)
    at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:200)
    at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:92)
    at com.amazonaws.hal.HalService.getRootResource(HalService.java:128)
    at com.amazonaws.services.apigateway.AmazonApiGateway.getApiGateway(AmazonApiGateway.java:113)
    at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:299)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
    at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    ... 3 more
```

So please tell me what i'm doing wrong if this should work? Because i'm not able to get it working...

**Comment by rpgreen** [comment]
Interesting - I haven't tested this specifically but that error message
appears to come from the AWS SDK default provider chain. There may be a
problem with the credentials/config. Does the AWS CLI work with this
configuration?

On Monday, 18 January 2016, Joris Conijn notifications@github.com wrote:

> Just tested it
> 
> aws-api-import.sh --update ${AWS_API_ID} --deploy ${AWS_API_STAGE} ${PWD}/AWS/API/swagger.yaml --profile MyRoleWithoutMFA --region ${REGION}
> 
> With the config:
> 
> [default]
> aws_access_key_id = ***
> aws_secret_access_key = ***
> 
> [profile MyRoleWithoutMFA]
> source_profile = default
> region = eu-west-1
> role_arn = arn:aws:iam::************:role/MyRoleWithoutMFA
> 
> arn:aws:iam::************:role/MyRoleWithoutMFA has the policy:
> 
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Action": "_",
>       "Resource": "_"
>     }
>   ]
> }
> 
> And the configured access key has the right to assume the role.
> 
> 2016-01-18 22:58:43,462 INFO - Using API Gateway endpoint https://apigateway.eu-west-1.amazonaws.com
> 2016-01-18 22:58:46,013 ERROR - Error importing API definition
> com.google.inject.ProvisionException: Unable to provision, see the following errors:
> 
> 1) Error in custom provider, com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
>   at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:63)
>   while locating com.amazonaws.services.apigateway.model.ApiGateway
>     for field at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.apiGateway(ApiGatewaySdkApiImporter.java:43)
>   while locating com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter
>   while locating com.amazonaws.service.apigateway.importer.SwaggerApiImporter
>     for parameter 1 at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.<init>(ApiGatewaySwaggerFileImporter.java:36)
>   while locating com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter
> 
> 1 error
>     at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
>     at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
> Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
>     at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
>     at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:229)
>     at com.amazonaws.hal.client.HalClient.getHalResource(HalClient.java:210)
>     at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:200)
>     at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:92)
>     at com.amazonaws.hal.HalService.getRootResource(HalService.java:128)
>     at com.amazonaws.services.apigateway.AmazonApiGateway.getApiGateway(AmazonApiGateway.java:113)
>     at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:64)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:299)
>     at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
>     at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
>     at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
>     at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
>     at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
>     at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
>     at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
>     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
>     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
>     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
>     at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
>     at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
>     at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
>     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
>     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
>     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
>     at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
>     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>     at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
>     ... 3 more
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/146#issuecomment-172666737
> .

##

**Comment by Nr18** [comment]
Yes the credentials are working:

```
$ aws apigateway get-rest-apis --profile MyRoleWithoutMFA
{
    "items": [
        {
            "createdDate": 1452179178,
            "id": "*********",
            "name": "MyAPI"
        }
    ]
}
```

Are you using STS for the temporary credential retrieval? I had a similar issue with the PHP SDK there i needed to do the following:

```
$client = new StsClient( [ 'version'   => 'latest', 'region'    => 'us-east-1' ]);

$assumeRole = [
    'RoleArn'           => 'arn:aws:iam::************:role/MyRoleWithoutMFA',
    'RoleSessionName'   => 'MySession',
];

if( isset( $profileInfo['mfa_serial'] ) ) {
    $assumeRole['SerialNumber'] = $profileInfo['mfa_serial'];
    $assumeRole['TokenCode'] = readline("Enter MFA Token for {$profileInfo['mfa_serial']}: ");
}    

$credentials = $client->createCredentials( $client->assumeRole( $assumeRole ) );
```

As you can see if i configured a mfa_serial in the profile i request the token from the user input.

This configuration setup works with the AWS CLI and is valid see: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html so it would be very nice to support this in this tool as well.

**Comment by rpgreen** [comment]
Thanks for bringing this to our attention. 

Does the error message refer to the assumed role or the user associated with the key pair?

"Caused by: com.amazonaws.AmazonServiceException: User: arn:aws:iam::***********_:user/**_******\* is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:eu-west-1::/ (Service: null; Status Code: 403; Error Code: null; Request ID: *******)"

It appears the AWS SDK is not assuming the role specified. This may be a CLI-only feature. We will investigate. You may want to try bumping the AWS SDK dependency version in the pom file to the latest version to see if that makes a difference.

**Comment by Nr18** [comment]
Depends i did 2 tests:
- 1 IAM User that should assume a IAM Role with MFA required boolean set in the policy and config.
- 1 IAM User that should assume a IAM Role with no MFA.

The line you mentioned corresponds with the first test, i guess that the AWS CLI has done it's own implementation for the STS Service instead of adding a generic method to the SDK's. 

MFA sessions in the AWS CLI tool expire after an hour, and they don't renew the credentials automatically this does not match the behaviour in the Web Console there they redirect and renew your credentials for you up to 12 hours i believe.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan

**Comment by n2ygk** [comment]
So assume role support is still broken and AWS API-Gateway documentation says to continue using this tool to import RAML. That doesn't sound like it should be closed.
