### ISSUE TITLE
BadRequestException: Invalid cache key - when trying to import Swagger file generated by aws console export

### ISSUE THREAD

**Issue by dukeatcoding** [awslabs/aws-apigateway-swagger-importer#148]
I exported a Swagger + API Gateway json definition of my running API Gateway configuration in Ireland and tried to import them with the apigateway-importer in usw-west-1. And got suprisingly an error. Since I didn't modified the exported .json, I have no clue why it should not work.

I attached the file only with modified IPs
[corporate-staging-swagger-integrations-noip.txt](https://github.com/awslabs/aws-apigateway-importer/files/105085/corporate-staging-swagger-integrations-noip.txt)

```
 16-01-26 15:51:56,040 INFO - Creating integration with type HTTP
2016-01-26 15:51:56,734 INFO - Creating method for api id tcnluavmhe and resource id n08h50 with method post
2016-01-26 15:51:57,287 INFO - Creating resource '{id}' on eo1zha
2016-01-26 15:51:58,114 INFO - Creating method response for api tcnluavmhe and method GET and status 200
2016-01-26 15:51:58,287 INFO - Found reference to existing model Empty
2016-01-26 15:51:58,634 INFO - Creating method parameter for api tcnluavmhe and method GET with name method.request.path.id
2016-01-26 15:51:58,823 INFO - Creating integration with type HTTP
2016-01-26 15:51:59,173 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid cache key parameter specified (Service: null; Status Code: 400; Error Code: null; Request ID: ac297d30-c43c-11e5-949f-9b2c477cd931)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
        at com.sun.proxy.$Proxy35.putIntegration(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:264)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:239)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$0(ApiGatewaySdkSwaggerApiImporter.java:177)
        at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:176)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:168)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2016-01-26 15:51:59,179 INFO - Deleting API tcnluavmhe
2016-01-26 15:51:59,796 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid cache key parameter specified (Service: null; Status Code: 400; Error Code: null; Request ID: ac297d30-c43c-11e5-949f-9b2c477cd931)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
        at com.sun.proxy.$Proxy35.putIntegration(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:264)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:239)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$0(ApiGatewaySdkSwaggerApiImporter.java:177)
        at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:176)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:168)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by balakataws** [comment]
Thanks for reporting this. This is a bug in export API. We are working on fixing this. 

Meanwhile, you can easily work around by editing the cacheKeyParameters from method.input.params.\* format to method.request.(querystring | header | path).\* format. In this case, you will be changing method.input.params.id to method.request.path.id

Sorry for any trouble this may have caused. Let us know if you need further assistance.

**Comment by dukeatcoding** [comment]
Your workaround seems to work, thank you.

Next step for me is to generate "new" swagger definitions from a script of mine and to update an existing configuration lets see how that works out.

**Comment by sredko** [comment]
@balakataws I still have this issue after it was reported 2 months ago. This issue seems breaking all functionality claimed to work here http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html that relates to API Gateway integration extensions. So I could not import as is exported file without manual corrections. Could you please help me understand the following:
- AWS API Gateway team doesn't consider import/export as important means to save/re-deploy API?, and if yes,
- What AWS API Gateway team can recommend to use for save/re-deploy API (AWS CLI? or something else?) It seems CloudFormation should be used instead of that importer for overall consistency, but it is not there. Do you have plans to move it there?

Thanks a lot!

**Comment by balakataws** [comment]
We will prioritize this fix. Sorry for any additional manual work this bug may have caused. 
Import/Export are very important features, and we are working on bringing them together to improve consistency and user experience.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
