### ISSUE TITLE
Invalid ARN specified in the request

### ISSUE THREAD

**Issue by zamn** [awslabs/aws-apigateway-swagger-importer#150]
Hi,

I'm trying to create an API via a swagger template file using your utility and I keep getting this error message: `com.amazonaws.services.apigateway.model.BadRequestException: Invalid ARN specified in the request (Service: null; Status Code: 400; Error Code: null; Request ID: 368ea7fe-c620-11e5-8f9d-491610cecdad)`

I can give more context if needed, but right now I'm simply automating my API creation process. So my flow looks like:

1) Create necessary Lambda function, record ARN
2) Using ARN from above, put it into swagger template
3) Run the command: `java -jar aws-apigateway-importer-1.0.3-SNAPSHOT-jar-with-dependencies.jar --create swagger.json --region us-west-2`

My swagger file is the following:

``` json
{
    "basePath": "/",
    "definitions": {
        "Empty": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "Empty Schema",
            "type": "object"
        },
        "Error": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "title": "Error Schema",
            "type": "object"
        }
    },
    "host": "blah.execute-api.us-west-2.amazonaws.com",
    "info": {
        "title": "MyAPI",
        "version": "2016-01-25T18:04:12Z"
    },
    "paths": {
        "/test": {
            "get": {
                "parameters": [
                    {
                        "in": "query",
                        "name": "id",
                        "required": false,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "200 response",
                        "headers": {},
                        "schema": {
                            "$ref": "#/definitions/Empty"
                        }
                    }
                },
                "x-amazon-apigateway-auth": {
                    "type": "aws_iam"
                },
                "x-amazon-apigateway-integration": {
                    "httpMethod": "POST",
                    "requestTemplates": {
                        "application/json": "{\n    \"id\": \"$input.params('id')\"\n}"
                    },
                    "responses": {
                        "default": {
                            "responseTemplates": {
                                "application/json": "__passthrough__"
                            },
                            "statusCode": "200"
                        }
                    },
                    "type": "aws",
                    "uri": "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:ACCOUNT_ID:function:MyFunction/invocations"
                }
            }
        }
    },
    "schemes": [
        "https"
    ],
    "swagger": "2.0"
}
```

The stack trace is:

``` bash
com.amazonaws.services.apigateway.model.BadRequestException: Invalid ARN specified in the request (Service: null; Status Code: 400; Error Code: null; Request ID: 66562fb7-c622-11e5-96ab-1f12a4ae9367)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
        at com.sun.proxy.$Proxy35.putIntegration(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:264)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:239)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$7(ApiGatewaySdkSwaggerApiImporter.java:177)
        at java.util.HashMap$EntrySet.forEach(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:176)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:168)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

The Lambda function is being created in the most basic way possible. Meaning that the IAM role has the most basic permissions, and there are just print statements in it. I just can't seem to figure out why this utility doesn't like my URI :\ 

As I said, if you need more information I would be more than happy to oblige

**Comment by zamn** [comment]
You can ignore this, there was a bug in the program generating our swagger file that ended up not having the correct URI.
