### ISSUE TITLE
RAML Importer: Integration Is Created Prematurely (Before Method Parameters Are Available)

### ISSUE THREAD

**Issue by arielatmuseami** [awslabs/aws-apigateway-swagger-importer#151]
I believe your ApiGatewaySdkRamlImport.java class has a few steps out of order.

While trying to import a properly structured RAML document and corresponding integration JSON file into an existing API in which I deleted all the resources via the AWS console (in order to start the import from near-scratch), I kept getting this error message:

```
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.request.header.Accept] (Service: null; Status Code: 400; Error Code: null; Request ID: fab2f1e3-c62c-11e5-ba5a-f7b1c4a9587f)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy29.putIntegration(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createIntegration(ApiGatewaySdkRamlApiImporter.java:305)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createMethod(ApiGatewaySdkRamlApiImporter.java:258)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createMethods(ApiGatewaySdkRamlApiImporter.java:182)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createResources(ApiGatewaySdkRamlApiImporter.java:151)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.createResources(ApiGatewaySdkRamlApiImporter.java:152)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkRamlApiImporter.updateApi(ApiGatewaySdkRamlApiImporter.java:102)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.updateApi(ApiGatewayRamlFileImporter.java:59)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importRaml(ApiImporterMain.java:178)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:141)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

I tried removing my integration configuration's requestParameters and found that the import then worked (minus the integration mappings I was hoping to use), so I became more confident in my RAML and JSON documents and dug into the source to see why the AWS API Gateway putMethod API thought that the required mappings didn't exist. Here's what I found:

In the java method "private void createMethod(final RestApi api, final Resource resource, final ActionType httpMethod, final Action action, boolean update) {" (line 208 as of commit 7573bb2), starting at line 258, you'll see the following block of code:

```
        createIntegration(resource, method, this.config);

        for (Map.Entry<String, UriParameter> entry : action.getResource().getUriParameters().entrySet()) {
            updateMethod(api, method, "path", entry.getKey(), entry.getValue().isRequired());
        }

        for (Map.Entry<String, Header> entry : action.getHeaders().entrySet()) {
            updateMethod(api, method, "header", entry.getKey(), entry.getValue().isRequired());
        }

        for (Map.Entry<String, QueryParameter> entry : action.getQueryParameters().entrySet()) {
            updateMethod(api, method, "querystring", entry.getKey(), entry.getValue().isRequired());
        }

        if (update) {
            cleanupMethod(api, method, "path", action.getResource().getUriParameters().keySet());
            cleanupMethod(api, method, "header", action.getHeaders().keySet());
            cleanupMethod(api, method, "querystring", action.getQueryParameters().keySet());
        }
```

Notice that the integration is taking place BEFORE method's path, header, and querystring method parameters are being set to the method. I tried moving the invocation of createIntegration() below the if(update) block, rebuilt the importer, and found that my API FINALLY started importing properly and fully.

For reference (and your own testing since your example RAML files in the tst/resources/raml folder don't appear to be setup properly), here's my RAML and integration configs:
RAML:

```
#%RAML 0.8

title: FOO TEST
version: 1.0.0

documentation:
  - title: FOO TEST
    content: |
      Foo foo foo.

mediaType: application/json

protocols:
  - https

baseUri: https://foo.com/

schemas:
  - Empty: |
      {
        "title": "Empty schema",
        "type": "object"
      }
  - Error: |
      {
        "title": "Error schema",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      }

/foo:
  /bar:
    get:
      description: >
        Foo.

      queryParameters:
        clientApp:
          description: String value identifying the client application.
          type: string
          required: false
          example: browser

      headers:
        Accept:
          description: |
            Foo.
          required: true
          type: string
          example: text/html

      responses:
        200:
          description: Foo.
          body:
            text/html:
              schema: Empty
        300:
          description: Foo
          body:
            text/html:
              schema: Empty
        400:
          description: Foo.
          body:
            text/html:
              schema: Empty
        500:
          description: Foo.
          body:
            text/html:
              schema: Empty
```

Integration JSON:

```
{
  "/foo/bar": {
    "get": {
      "auth": {
        "type": "none"
      },
      "integration": {
        "type": "http",
        "uri": "http://${stageVariables.fooDomain}/foo/bar",
        "httpMethod": "GET",
        "requestParameters": {
          "integration.request.querystring.clientApp": "method.request.querystring.clientApp",
          "integration.request.header.Accept": "method.request.header.Accept"
        },
        "responses": {
          "2\\d{2}": {
            "statusCode": "200",
            "responseTemplates": {
              "text/html": ""
            }
          },
          "3\\d{2}": {
            "statusCode": "300",
            "responseTemplates": {
              "text/html": ""
            }
          },
          "4\\d{2}": {
            "statusCode": "400",
            "responseTemplates": {
              "text/html": ""
            }
          },
          "5\\d{2}": {
            "statusCode": "500",
            "responseTemplates": {
              "text/html": ""
            }
          }
        }
      }
    }
  }
}
```

**Comment by rpgreen** [comment]
You're correct in that integration mappings should be applied AFTER the method parameters are defined. If you can get this working please send a PR

**Comment by arielatmuseami** [comment]
@rpgreen, will do.

**Comment by arielatmuseami** [comment]
@rpgreen, all set. See PR [#152](https://github.com/awslabs/aws-apigateway-importer/pull/152).

**Comment by rpgreen** [comment]
Merged. Much appreciated
