### ISSUE TITLE
Raml examples fail on create with NullPointerException

### ISSUE THREAD

**Issue by sophieher** [awslabs/aws-apigateway-swagger-importer#159]
Copy/pasted the [raml examples](https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/raml/apigateway.raml) and am getting the following error when attempting to create an api.

```
 ./aws-api-import.sh -t --create /tmp/schema.raml
2016-02-05 10:52:30,268 INFO - Using API Gateway endpoint https://apigateway.us-west-2.amazonaws.com
2016-02-05 10:52:32,302 INFO - Attempting to create API from RAML definition. RAML file: /tmp/schema.raml
2016-02-05 10:52:32,305 ERROR - Error importing API definition
java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1025)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
    at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:218)
    at org.raml.parser.utils.StreamUtils.reader(StreamUtils.java:45)
    at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:102)
    at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:78)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.parse(ApiGatewayRamlFileImporter.java:73)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewayRamlFileImporter.importApi(ApiGatewayRamlFileImporter.java:47)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importRaml(ApiImporterMain.java:171)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:141)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by jackrk** [comment]
Could be an issue with the input file, possibly permissions. That's what the stack trace seems to indicate.

**Comment by sophieher** [comment]
Yeah, the input is the raml file from the aws-apigateway-importer examples, so I'm stuck on what format is required if not this.

**Comment by yyamano** [comment]
@sophieher it doesn't work with absolute path for some reason.

```
% cp tst/resources/raml/example.raml /tmp/example.raml
% ./aws-api-import.sh -r ap-northeast-1 -c /tmp/example.raml
2016-03-17 13:43:00,268 INFO - Using API Gateway endpoint https://apigateway.ap-northeast-1.amazonaws.com
2016-03-17 13:43:02,459 INFO - Attempting to create API from RAML definition. RAML file: /tmp/example.raml
2016-03-17 13:43:02,469 ERROR - Error importing API definition
java.lang.NullPointerException
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
```

```
% ./aws-api-import.sh -r ap-northeast-1 -c tst/resources/raml/example.raml
2016-03-17 13:43:12,915 INFO - Using API Gateway endpoint https://apigateway.ap-northeast-1.amazonaws.com
2016-03-17 13:43:14,398 INFO - Attempting to create API from RAML definition. RAML file: tst/resources/raml/example.raml
2016-03-17 13:43:14,617 INFO - Creating API with name Example API
```

**Comment by yyamano** [comment]
raml-java-parser doesn't like absolute path. See https://github.com/raml-org/raml-java-parser/issues/74

**Comment by sophieher** [comment]
interesting. Thanks @yyamano for the explanation. :+1:
