### ISSUE TITLE
Resource with id 'someId' has a conflicting path

### ISSUE THREAD

**Issue by hari-tw** [awslabs/aws-apigateway-swagger-importer#161]
I am trying to import the swagger config (uber.json or petstore-expanded.json), but with no luck.

I am getting the following error, that resource with id "someId" has a conflicting path. Why do we create the resource when it already exists?

```
2016-02-07` 20:22:18,967 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.ConflictException: Resource with id 'ty7owb' has a conflicting path (Service: null; Status Code: 409; Error Code: null; Request ID: 62a65427-cdaa-11e5-812d-1d06d06a60fa)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy31.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createResource(ApiGatewaySdkApiImporter.java:251)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:165)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2016-02-07 20:22:18,968 INFO - Deleting API 6btem6k59i
2016-02-07 20:22:19,716 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Resource with id 'ty7owb' has a conflicting path (Service: null; Status Code: 409; Error Code: null; Request ID: 62a65427-cdaa-11e5-812d-1d06d06a60fa)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy31.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createResource(ApiGatewaySdkApiImporter.java:251)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:165)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at `com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by hari-tw** [comment]
I am able to get around the issue, Had to revert @rpgreen refactoring commit **c59f8ac** which reduces the number of getResources() call. But then any new resource created will no be held locally, so it goes ahead and tries to create an already existing resource. 

Ill try and optimise this code and create a pull request.

Cheers

**Comment by rpgreen** [comment]
PR would be appreciated

**Comment by rpgreen** [comment]
Just pushed a fix for this - please let me know if still having issues
