### ISSUE TITLE
com.amazonaws.services.apigateway.model.ConflictException: Resource with id '<something>' has a conflicting path

### ISSUE THREAD

**Issue by flashsnake-so** [awslabs/aws-apigateway-swagger-importer#162]
I checked that I don't have the conflicted path, like:

/application/xyz
/application/abc

``` sh
2016-02-07 13:48:53,167 INFO - Creating model for api id 49oxtoxvgi with name CampaignList
2016-02-07 13:48:53,171 INFO - Generated json-schema for model CampaignList: {"type":"array","items":{"type":"object"},"definitions":{}}
2016-02-07 13:48:53,415 INFO - Creating resource 'dev' on 9vv43chy78
2016-02-07 13:48:53,682 INFO - Creating resource 'application' on nu4ex6
2016-02-07 13:48:53,960 INFO - Found input model reference Application
2016-02-07 13:48:54,190 INFO - Creating method response for api 49oxtoxvgi and method PATCH and status 200
2016-02-07 13:48:54,300 INFO - Found reference to existing model Application
2016-02-07 13:48:54,537 INFO - Creating method response for api 49oxtoxvgi and method PATCH and status 400
2016-02-07 13:48:54,639 INFO - Found reference to existing model Error
2016-02-07 13:48:54,859 INFO - Creating integration with type AWS
2016-02-07 13:48:55,475 INFO - Creating method for api id 49oxtoxvgi and resource id kpr7ad with method patch
2016-02-07 13:48:55,675 INFO - Creating method response for api 49oxtoxvgi and method GET and status 200
2016-02-07 13:48:55,782 INFO - Found reference to existing model Application
2016-02-07 13:48:55,992 INFO - Creating method parameter for api 49oxtoxvgi and method GET with name method.request.querystring.applicationId
2016-02-07 13:48:56,097 INFO - Creating integration with type AWS
2016-02-07 13:48:56,493 INFO - Creating method for api id 49oxtoxvgi and resource id kpr7ad with method get
2016-02-07 13:48:56,693 INFO - Creating method response for api 49oxtoxvgi and method OPTIONS and status 200
2016-02-07 13:48:56,792 INFO - Found reference to existing model Empty
2016-02-07 13:48:57,013 INFO - Creating method parameter for api 49oxtoxvgi and method OPTIONS with name method.request.querystring.applicationId
2016-02-07 13:48:57,124 INFO - Creating integration with type MOCK
2016-02-07 13:48:57,537 INFO - Creating method for api id 49oxtoxvgi and resource id kpr7ad with method options
2016-02-07 13:48:57,538 INFO - Creating resource 'dev' on 9vv43chy78
2016-02-07 13:48:57,765 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.ConflictException: Resource with id 'nu4ex6' has a conflicting path (Service: null; Status Code: 409; Error Code: null; Request ID: 972d8b4a-cde4-11e5-8750-c595d344f9e0)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy31.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createResource(ApiGatewaySdkApiImporter.java:251)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:165)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2016-02-07 13:48:57,766 INFO - Deleting API 49oxtoxvgi
2016-02-07 13:48:58,606 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Resource with id 'nu4ex6' has a conflicting path (Service: null; Status Code: 409; Error Code: null; Request ID: 972d8b4a-cde4-11e5-8750-c595d344f9e0)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy31.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createResource(ApiGatewaySdkApiImporter.java:251)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:165)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

Here is my YAML:

``` yaml

---
swagger: "2.0"
info:
  version: "2016-01-31T22:24:51Z"
  title: "<<you never know>>"
host: "<<not going to tell you>>"
basePath: "/dev"
schemes:
- "https"
paths:
  /application:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "applicationId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Application"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"applicationId\": \"$input.params('applicationId')\"\
            \ \n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdGetApplication/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters: 
      - name: "applicationId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,PATCH'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
    patch:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Application"
        required: true
        schema:
          $ref: "#/definitions/Application"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Application"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/Error"
          headers: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
          Bad Request:.*:
            statusCode: "400"
        requestTemplates:
          application/json: "__passthrough__"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdUpdateApplication/invocations"
        httpMethod: "POST"
        type: "aws"
  /campaign:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "numberOfFollowers"
        in: "query"
        required: false
        type: "string"
      - name: "campaignIds"
        in: "query"
        required: false
        type: "string"
      - name: "count"
        in: "query"
        required: false
        type: "string"
      - name: "ageRange"
        in: "query"
        required: false
        type: "string"
      - name: "startKey"
        in: "query"
        required: false
        type: "string"
      - name: "tags"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/CampaignList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "#if (\"$input.params('numberOfFollowers')\" != \"\")\
            \ \n    #set($numberOfFollowers = $input.params('numberOfFollowers'))\n\
            #else \n    #set($numberOfFollowers = 0)\n#end\n\n{\n    \"ageRange\"\
            \ : \"$input.params('ageRange')\",\n    \"numberOfFollowers\" : $numberOfFollowers,\n\
            \    \"count\" : $input.params('count'),\n    \"startKey\" : \"$input.params('startKey')\"\
            ,\n    \"campaignIds\" : \"$util.urlDecode($input.params('campaignIds'))\"\
            \n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdGetCampaign/invocations"
        httpMethod: "POST"
        type: "aws"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Campaign"
        required: true
        schema:
          $ref: "#/definitions/Campaign"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "__passthrough__"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdCreateCampaign/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /campaign/application:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "campaignId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ApplicationResponseList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"campaignId\" : \"$input.params('campaignId')\"\
            \n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdGetApplication/invocations"
        httpMethod: "POST"
        type: "aws"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Application"
        required: true
        schema:
          $ref: "#/definitions/Application"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/Error"
          headers: {}
        409:
          description: "409 response"
          schema:
            $ref: "#/definitions/Error"
          headers: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
          Bad Request.*:
            statusCode: "400"
            responseTemplates:
              application/json: "__passthrough__"
          The conditional request failed.*:
            statusCode: "409"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"campaignId\": \"$input.json('$.campaignId')\"\
            ,\n    \"application\" : $input.json('$')\n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdCreateApplication/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters:
      - name: "campaignId"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "Application"
        required: true
        schema:
          $ref: "#/definitions/Application"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,OPTIONS,PATCH'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
    patch:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Application"
        required: true
        schema:
          $ref: "#/definitions/Application"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Application"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "__passthrough__"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdUpdateApplication/invocations"
        httpMethod: "POST"
        type: "aws"
  /insights/facebook:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "postId"
        in: "query"
        required: false
        type: "string"
      - name: "accessToken"
        in: "query"
        required: false
        type: "string"
      - name: "pageId"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Insight"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/Error"
          headers: {}
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
          Bad Request:.*:
            statusCode: "400"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"accessToken\" : \"$input.params('accessToken')\"\
            ,\n    \"pageId\" : \"$input.params('pageId')\",\n    \"postId\" : \"\
            $input.params('postId')\"\n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:GetFacebookAudience/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /insights/facebook/pages:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "accessToken"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/FacebookPages"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"accessToken\" : \"$input.params('accessToken')\"\
            \n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:GetFacebookPages/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /insights/facebook/schedulepost:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "SchedulePostRequest"
        required: true
        schema:
          $ref: "#/definitions/SchedulePostRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "__passthrough__"
        uri: "http://${stageVariables.agendaUrl}/schedule"
        httpMethod: "POST"
        type: "http"
    options:
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /insights/twitter:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/TwitterInsight"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        404:
          description: "404 response"
          schema:
            $ref: "#/definitions/Empty"
          headers: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
          Not found:.*:
            statusCode: "404"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"userId\": \"$input.params('userId')\"\n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:GetTwitterAudience/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /user:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "User"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/User"
          headers: {}
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/Error"
          headers: {}
        500:
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
          headers: {}
        409:
          description: "409 response"
          headers: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: "__passthrough__"
          The conditional request failed.*:
            statusCode: "409"
        requestTemplates:
          application/json: "__passthrough__"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdCreateUser/invocations"
        httpMethod: "POST"
        type: "aws"
  /user/application:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ApplicationResponseList"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\n    \"userId\": \"$input.params('userId')\"\n}"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:a:function:LambdGetApplication/invocations"
        httpMethod: "POST"
        type: "aws"
    options:
      produces:
      - "application/json"
      parameters: 
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "__passthrough__"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
  User:
    type: "object"
    required:
    - "email"
    properties:
      userId:
        type: "string"
      facebook:
        type: "string"
      email:
        type: "string"
      campaignIds:
        type: "array"
        items: 
          type: "string"
      profile:
        type: "object"
        properties:
          website:
            type: "string"
          gender:
            type: "string"
          facebookDefaultPageId:
            type: "string"
          name:
            type: "string"
          location:
            type: "string"
          picture:
            type: "string"
      tokens:
        type: "array"
        items:
          type: "object"
          properties:
            token:
              type: "string"
            accessToken:
              type: "string"
      __v:
        type: "integer"
      instagram:
        type: "string"
  Campaign:
    type: "object"
    required:
    - "campaignId"
    properties:
      campaignId:
        type: "string"
      createTime:
        type: "string"
      updateTime:
        type: "string"
      details:
        type: "string"
      numberOfViews:
        type: "integer"
      status:
        type: "string"
      thumbnail:
        type: "string"
      topic:
        type: "string"
      numberOfFollowers:
        type: "integer"
      minAge:
        type: "integer"
      maxAge:
        type: "integer"
  Insight:
    type: "object"
    properties:
      gender:
        type: "object"
        properties:
          female:
            type: "integer"
          male:
            type: "integer"
      likes:
        type: "integer"
      location:
        type: "object"
        properties: {}
      age:
        type: "object"
        properties: {}
      comments:
        type: "integer"
      sharedposts:
        type: "object"
        properties: {}
  Error:
    type: "object"
    properties:
      message:
        type: "string"
  SchedulePostRequest:
    type: "object"
    required:
    - "accessToken"
    - "applicationId"
    - "campaignId"
    - "message"
    - "pageId"
    properties:
      accessToken:
        type: "string"
      message:
        type: "string"
      pageId:
        type: "string"
      applicationId:
        type: "string"
      campaignId:
        type: "string"
  FacebookPages:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          type: "string"
  ApplicationResponseList:
    type: "array"
    items:
      type: "object"
      properties:
        reason:
          type: "string"
        actionTime:
          type: "string"
        createTime:
          type: "string"
        campaignId:
          type: "string"
        updateTime:
          type: "string"
        applicationId:
          type: "string"
        message:
          type: "string"
        userId:
          type: "string"
        status:
          type: "string"
  Application:
    type: "object"
    required:
    - "applicationId"
    - "userId"
    properties:
      applicationId:
        type: "string"
      reason:
        type: "string"
      campaignId:
        type: "string"
      applicant:
        type: "object"
        properties:
          actionTime:
            type: "string"
      createTime:
        type: "string"
      userId:
        type: "string"
      owner:
        type: "object"
        properties:
          actionTime:
            type: "string"
      updateTime:
        type: "string"
      status:
        type: "string"
  TwitterInsight:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      screen_name:
        type: "string"
      gender:
        type: "string"
      avatar:
        type: "string"
      followers:
        type: "integer"
      friends:
        type: "integer"
      posts:
        type: "integer"
      monthsregistered:
        type: "integer"
      yearsregistered:
        type: "number"
      postpermonth:
        type: "integer"
      city:
        type: "string"
      country:
        type: "string"
  CampaignList:
    type: "array"
    items:
      type: "object"
      properties:
        thumbnail:
          type: "string"
        numberOfFollowers:
          type: "integer"
        createTime:
          type: "string"
        maxAge:
          type: "integer"
        campaignId:
          type: "string"
        numberOfViews:
          type: "integer"
        minAge:
          type: "integer"
        topic:
          type: "string"
        updateTime:
          type: "string"
        details:
          type: "string"
        status:
          type: "string"
```

**Comment by flashsnake-so** [comment]
I found out the problem.

This importer does not like the sub path so much.  I removed all the sub paths and works fine.
