### ISSUE TITLE
`example` schema object attribute crashing importer

### ISSUE THREAD

**Issue by zanona** [awslabs/aws-apigateway-swagger-importer#177]
Apparently when having the `example` parameter for properties set in object will cause the importer to crash and stop the import process?

As far as I could understand the declaration of `example` on model objects is valid and it helps quite a lot for documentation purposes.

``` yaml
swagger: '2.0'
info:
  ...
paths:
  ...
definitions:
  User:
    type: object
    properties:
      name:
        type: string
        example: John Applesed #<===
      email:
        type: string
        format: email
        example: john@domain.com #<===
```

**Comment by kahouieong** [comment]
It should not cause the importer to crash, but the importer will ignore this property when it is importing the API.

**Comment by zanona** [comment]
Yes, that was I have expected initially too, but surprisingly it's crashing?

[![asciicast](https://asciinema.org/a/7036btvajb27yklzxxbe40nch.png)](https://asciinema.org/a/7036btvajb27yklzxxbe40nch)

Here is the error log:

``` sh
2016-03-03 22:18:57,010 INFO - Attempting to update API from Swagger definition. API identifier: b76joivtw4 Swagger file: swagger.yaml
reading from swagger.yaml
2016-03-03 22:18:57,118 INFO - Parsed Swagger with 1 paths
2016-03-03 22:18:57,331 INFO - Updating model for api id b76joivtw4 and model name User
2016-03-03 22:18:57,507 INFO - Generated json-schema for model User: {"type":"object","properties":{"name":{"type":"string","example":"foo"}},"definitions":{}}
2016-03-03 22:18:57,629 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: ecd839c6-e18d-11e5-a0d5-75bba301046c)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1369)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:913)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:631)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:400)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:362)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:311)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.patchResource(HalClient.java:162)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:137)
    at com.sun.proxy.$Proxy32.updateModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.updateModel(ApiGatewaySdkApiImporter.java:158)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModel(ApiGatewaySdkSwaggerApiImporter.java:405)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModels(ApiGatewaySdkSwaggerApiImporter.java:396)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:86)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:161)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by kahouieong** [comment]
I did a little bit investigation. There is an issue on how the API importer generates the JSON schema for the swagger model. JSON schema doesn't allow to have `example` as property, but swagger model does. It fails on the API Gateway service side validation.

I will add an item in our backlog to fix this issue. Thank you for letting us know.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
