### ISSUE TITLE
Throttling exception during import

### ISSUE THREAD

**Issue by b3ngineer** [awslabs/aws-apigateway-swagger-importer#179]
The import process throws an exception during execution: 

com.amazonaws.services.apigateway.model.TooManyRequestsException: Too Many Requests (Service: null; Status Code: 429; Error Code: ThrottlingException; Request ID: ...)
at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)

It started out as a sporadic error, but has become something that occurs every time we try to import the swagger file now.  We have a total of 66 resources in our API, half of which are OPTIONS for CORS.  So, it's a small-ish API.   We are not staging the API before or after importing as any kind of automated step.

It occurs no matter when we run it (first thing in the morning, at night).  It fails even if it's the first and only import attempted in several hours.

**Comment by b3ngineer** [comment]
Fixed with commit bcc46ab and java version 1.8.0_74-b02.
