### ISSUE TITLE
Definitions need to support "Example"

### ISSUE THREAD

**Issue by mikestokes** [awslabs/aws-apigateway-swagger-importer#18]
Add support for the "example" property to definitions in Swagger files. This will allow us to keep the example text in our Swagger generated documentation.

Currently if you have the example property:

```
"definitions": {
        "Project": {
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "name": {
                    "type": "string",
                    "example": "my project name"
                }
            }
        }
    }
```

Results in the following exception being thrown:

```
2015-08-14 14:44:47,486 INFO - Parsed Swagger with 2 paths
2015-08-14 14:44:48,232 INFO - Updating model for api id ********* and model name Project
2015-08-14 14:44:48,534 INFO - Generated json-schema for model Project: {"required":["name"],"properties":{"name":{"type":"string","example":"myproject"}},"definitions":{}}
2015-08-14 14:44:49,011 ERROR - Error importing API from Swagger
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 6e3405f6-422e-11e5-8811-7975d3f2c549)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.patchResource(HalClient.java:162)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:137)
    at com.sun.proxy.$Proxy32.updateModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModel(ApiGatewaySdkSwaggerApiImporter.java:223)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModel(ApiGatewaySdkSwaggerApiImporter.java:571)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModels(ApiGatewaySdkSwaggerApiImporter.java:560)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:109)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:107)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

**Comment by rpgreen** [comment]
"example" property is specific to Swagger models and is not supported by the json-schema spec. 
Tracking this in #10
