### ISSUE TITLE
Issue while using x-amazon-apigateway-integration option

### ISSUE THREAD

**Issue by romain-nio** [awslabs/aws-apigateway-swagger-importer#183]
Hi,

I tried to use "x-amazon-apigateway-integration" option in my swagger API definition. I tried this :

```
 /visit:
    post:
      tags:
        - visit
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2016-03-16/functions/arn:aws:lambda:eu-west-1:624074376577:function:NightForecast_DataCollection/invocations
        credentials: arn:aws:iam::624074376577:role/LambdaWriteKinesisFirehose
        httpMethod: POST
        requestTemplates:
          application/json: visit
```

it failed with the fowlloing error : 

```
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:275)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:268)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:241)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$0(ApiGatewaySdkSwaggerApiImporter.java:179)
    at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:178)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:170)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:69)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:155)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
2016-03-16 10:20:34,035 INFO - Deleting API sll21dd4g9
2016-03-16 10:20:34,455 ERROR - Error importing API definition
```

I don't understand of to build the URI for the lambda function. Your example is :
`arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:MY_ACCT_ID:function:helloWorld/invocations`

why is there a date like "path/2015-03-31" ? By which string do I have to replace it ?

For the credentials role (field "credential"), what type of role do I need to add in IAM ? IS"lambda:InvokeFunction" role on the correct Lambda ARN enough ?

Thanks,
Romain

**Comment by rpgreen** [comment]
ARN format:

arn:aws:apigateway:[YOUR REGION]:lambda:path/2015-03-31/functions/[YOUR LAMBDA FUNCTION ARN]/invocations

InvokeFunction should be all you need in the role policy. Please have a read through the service documentation for more details
