### ISSUE TITLE
Update Error: Error Importing API from Swagger

### ISSUE THREAD

**Issue by austencollins** [awslabs/aws-apigateway-swagger-importer#2]
Ok, I have created an API through the import tool.  Which was exciting by the way.  Really nice work here guys!

Now, I'm attempting to update my API and getting the following error:

```
  $ ./aws-api-import.sh --update ca82kasf84 ../api_v1.json
  2015-07-21 13:38:19,997 INFO - Attempting to update API from Swagger definition. API identifier: ca82kasf84 Swagger file: ../api_v1.json
  reading from ../api_v1.json
  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
  SLF4J: Defaulting to no-operation (NOP) logger implementation
  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  2015-07-21 13:38:20,075 INFO - Parsed Swagger with 1 paths
  2015-07-21 13:38:20,364 ERROR - Error importing API from Swagger java.lang.NullPointerException
      at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModels(ApiGatewaySdkSwaggerApiImporter.java:549)
      at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:106)
      at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
      at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:104)
at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:62)
```

**Comment by rpgreen** [comment]
This affects updating and API when no definitions are defined. I have added a fix for this. Alternatively you could add an empty definitions section to get around this.
