### ISSUE TITLE
Error Importing API from Swagger on Create

### ISSUE THREAD

**Issue by bholbrook73** [awslabs/aws-apigateway-swagger-importer#23]
I'm receiving errors using the importer... I'm not sure of the problem. Output below with sample of file (it's a large file).

**Call**
`./aws-api-import.sh --create ../api-public-deploy/output/1440628343409.json`

**Output**

```
2015-08-26 15:32:30,900 INFO - Attempting to create API from Swagger definition. Swagger file: ../api-public-deploy/output/1440628343409.json
reading from ../api-public-deploy/output/1440628343409.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from ../api-public-deploy/output/1440628343409.json
2015-08-26 15:32:30,954 ERROR - Error importing API from Swagger
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.getApiName(ApiGatewaySdkSwaggerApiImporter.java:238)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:87)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

**1440628343409.json**

``` json
{
  "apiVersion": 1,
  "swaggerVersion": "1.2",
  "basePath": "https://{hidden}.execute-api.us-west-2.amazonaws.com",
  "resourcePath": "/alpha",
  "apis": [
    {
      "path": "/api/v1/auth",
      "description": "Create a new user authentication (Login)",
      "operations": [
        {
          "method": "POST",
          "authorizations": {},
          "summary": "Create a new user authentication (Login)",
          "nickname": "apiv1auth",
          "notes": "Create a new user authentication (Login).",
          "type": "void",
          "parameters": [
            {
              "type": "apiv1auth",
              "defaultValue": null,
              "required": true,
              "name": "body",
              "paramType": "body"
            },
            {
              "type": "string",
              "description": "Distributed Organization API Key",
              "require": true,
              "name": "x-api-key",
              "paramType": "header"
            }
          ],
          "responseMessages": [],
          "consumes": [
            "application/json"
          ],
          "x-amazon-apigateway-integration": {
            "type": "http",
            "uri": "https://{hidden}/api/v1/auth",
            "httpMethod": "POST",
            "requestParameters": {}
          }
        }
      ]
    },
    {
      "path": "/api/v1/users/{user_id}/devices",
      "description": "Get devices for user",
      "operations": [
        {
          "method": "GET",
          "authorizations": {},
          "summary": "Get devices for user",
          "nickname": "apiv1usersuser_iddevices",
          "notes": "Notes...",
          "type": "void",
          "parameters": [
            {
              "type": "string",
              "description": "Authentication Token",
              "required": true,
              "name": "authorization",
              "paramType": "header"
            },
            {
              "type": "integer",
              "description": "User Id devices belong to.",
              "defaultValue": null,
              "minimum": 0,
              "name": "user_id",
              "paramType": "path"
            },
            {
              "type": "integer",
              "description": "Network ID that devices are on.",
              "defaultValue": null,
              "minimum": 1,
              "name": "network_id",
              "paramType": "query"
            },
            {
              "type": "string",
              "description": "Distributed Organization API Key",
              "require": true,
              "name": "x-api-key",
              "paramType": "header"
            }
          ],
          "responseMessages": [],
          "x-amazon-apigateway-integration": {
            "type": "http",
            "uri": "https://{hidden}/api/v1/users/{user_id}/devices",
            "httpMethod": "GET",
            "requestParameters": {
              "integration.request.header.authorization": "method.request.header.authorization",
              "integration.request.path.user_id": "method.request.path.user_id",
              "integration.request.queryString.network_id": "method.request.queryString.network_id"
            }
          }
        }
      ]
    }
  ],
  "models": {
    "apiv1auth": {
      "id": "apiv1auth",
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "description": "Username",
          "required": true
        },
        "password": {
          "type": "string",
          "description": "Password",
          "required": true
        }
      }
    },
    "apiv1users": {
      "id": "apiv1users",
      "type": "object",
      "properties": {
        "firstname": {
          "type": "string",
          "description": "First name",
          "required": true
        },
        "lastname": {
          "type": "string",
          "description": "Last name",
          "required": true
        },
        "company": {
          "type": "string",
          "description": "Company name",
          "required": true
        },
        "email": {
          "type": "string",
          "description": "Email Address",
          "required": true
        },
        "password": {
          "type": "string",
          "description": "Password",
          "required": true
        },
        "confirm": {
          "type": "string",
          "description": "Password Confirmation",
          "required": true
        },
        "phone": {
          "type": "string",
          "description": "Phone number",
          "required": true
        }
      }
    }
  }
}
```

**Comment by rpgreen** [comment]
Try adding the info object at the top level. i.e. 

```
"info": {
        "title": "My API"
    }
```

Also the basePath field in the context of this tool is just used to prefix the resource paths. The API Gateway endpoint URL will automatically be generated based on your region configuration. Your basePath could be "/api/v1" for example
