### ISSUE TITLE
swagger 2.0 compatibility?

### ISSUE THREAD

**Issue by javierjeronimo** [awslabs/aws-apigateway-swagger-importer#26]
```
2015-08-31 17:12:32,751 INFO - Attempting to create API from Swagger definition. Swagger file: ../api-doc/swagger.json
reading from ../api-doc/swagger.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.parameters.PathParameter["default"]) (through reference chain: com.wordnik.swagger.models.Swagger["parameters"]->java.util.LinkedHashMap["asset_types"])
reading from ../api-doc/swagger.json
Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.parameters.PathParameter["default"]) (through reference chain: com.wordnik.swagger.models.Swagger["parameters"]->java.util.LinkedHashMap["asset_types"])
2015-08-31 17:12:32,912 ERROR - Error importing API from Swagger
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.getApiName(ApiGatewaySdkSwaggerApiImporter.java:238)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:87)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

**Comment by rpgreen** [comment]
Swagger 2.0 is supported. Try adding a top-level info object:

```
    "info":{
        "title":"My API
    }
```

**Comment by javierjeronimo** [comment]
Will try, thank you.

**Comment by javierjeronimo** [comment]
It already had:

```
{
    "swagger": "2.0",
    "info": {
        "title": "Genexies Mobile MusicShop API v3",
[...]
```

**Comment by rpgreen** [comment]
From the logs it looks like your swagger file is not getting parsed correctly. You could try upgrading the swagger dependency versions in the pom file, similar to this pull request https://github.com/awslabs/aws-apigateway-swagger-importer/pull/13.

If that doesn't work please open an issue with swagger parser/core or send me the file and I'll take a look.
