### ISSUE TITLE
No integration defined for method

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-apigateway-swagger-importer#29]
Hi,

After some massaging of our existing Swagger docs I have successfully got an API in Amazon API Gateway.

However whenever I try to deploy this resource I'm receiving the following error:

```
com.amazonaws.services.apigateway.model.BadRequestException: No integration defined for method (Service: null; Status Code: 400; Error Code: null; Request ID: e64dddba-51d3-11e5-b141-a1f953910c1b)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy27.createDeployment(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.deploy(ApiGatewaySdkSwaggerApiImporter.java:121)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.deploy(ApiGatewaySwaggerFileImporter.java:63)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:111)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

Any advice if this is caused by my Swagger docs missing data? (1.2 -> 2.0 upgrade)

**Comment by rpgreen** [comment]
Standard Swagger is missing some information required to deploy an API in
API gateway. Your methods will need to include the
x-amazon-apigateway-integration extension. Have a look at the readme or
apigateway.json file for examples.

On Wednesday, September 2, 2015, dddanmar notifications@github.com wrote:

> Hi,
> 
> After some massaging of our existing Swagger docs I have successfully got
> an API in Amazon API Gateway.
> 
> However whenever I try to deploy this resource I'm receiving the following
> error:
> 
> com.amazonaws.services.apigateway.model.BadRequestException: No integration defined for method (Service: null; Status Code: 400; Error Code: null; Request ID: e64dddba-51d3-11e5-b141-a1f953910c1b)
>     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
>     at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
>     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
>     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
>     at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
>     at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
>     at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
>     at com.sun.proxy.$Proxy27.createDeployment(Unknown Source)
>     at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.deploy(ApiGatewaySdkSwaggerApiImporter.java:121)
>     at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.deploy(ApiGatewaySwaggerFileImporter.java:63)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:111)
>     at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
> 
> Any advice if this is caused by my Swagger docs missing data? (1.2 -> 2.0
> upgrade)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-swagger-importer/issues/29.

##

**Comment by ghost** [comment]
Thank you, I'm a fool, appreciate the nudge in the right direction.
