### ISSUE TITLE
Swagger body parameter causing NullPointerException

### ISSUE THREAD

**Issue by AaronRustad** [awslabs/aws-apigateway-swagger-importer#32]
I have an issue updating the API when a body parameter is defined for Swagger.

If I update the API with the following Swagger configuration (note body included) when there are no methods defined in AAG

![api_gateway](https://cloud.githubusercontent.com/assets/17159/9738572/62181ffc-5609-11e5-8a9e-9cadbc3e5ccb.jpg)

``` json
{  
  "swagger":"2.0",
  "info":{  
    "version":"v1",
    "title":"{hidden} API",
    "description":"Test our API services using I/O Docs. You can also view our written documentation.",
    "termsOfService":"http://www.{hidden}.com/docs/SNI-terms.pdf",
    "contact":{  
      "name":"support@{hidden}.com"
    }
  },
  "host":"api.{hidden}.com",
  "basePath":"/v1",
  "consumes":[  
    "application/json"
  ],
  "produces":[  
    "application/json"
  ],
  "definitions":{  

  },
  "paths":{  
    "/videos/{id}/metadata":{  
      "put":{  
        "summary":"Update Video Metadata",
        "description":"Update metadata for an an existing video",
        "operationId":"metadata",
        "tags":[  
          "Videos"
        ],
        "responses":{  
          "200":{  
            "headers":{  
              "Access-Control-Allow-Headers":{  
                "type":"string"
              },
              "Access-Control-Allow-Methods":{  
                "type":"string"
              },
              "Access-Control-Allow-Origin":{  
                "type":"string"
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"api_key",
            "in":"query",
            "required":true,
            "type":"string"
          },
          {  
            "name":"id",
            "description":"The hosted location of a video thumbnail (an http or https URL)",
            "in":"path",
            "required":false,
            "type":"string"
          },
          {  
            "name":"body",
            "in":"body",
            "required":true,
            "type":"string"
          }
        ],
        "x-amazon-apigateway-integration":{  
          "type":"http",
          "httpMethod":"PUT",
          "uri":"http://app.{hidden}.com/api/v1/videos/{id}/metadata",
          "responses":{  
            "2\\d{2}":{  
              "statusCode":"200",
              "responseParameters":{  
                "method.response.header.Access-Control-Allow-Headers":"'Content-Type,X-Amz-Date,Authorization'",
                "method.response.header.Access-Control-Allow-Methods":"'GET,POST'",
                "method.response.header.Access-Control-Allow-Origin":"'*'"
              }
            }
          },
          "requestParameters":{  
            "integration.request.querystring.api_key":"method.request.querystring.api_key",
            "integration.request.path.id":"method.request.path.id"
          }
        }
      }
    }
  }
}
```

I get the following exception:

``` bash
ip-192-168-2-29:aws-apigateway-swagger-importer arustad (master)$ ./aws-api-import.sh --update cddfwfu745 /tmp/swagger.json --deploy beta
2015-09-08 09:01:43,639 INFO - Attempting to update API from Swagger definition. API identifier: cddfwfu745 Swagger file: /tmp/swagger.json
reading from /tmp/swagger.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2015-09-08 09:01:43,709 INFO - Parsed Swagger with 1 paths
2015-09-08 09:01:44,448 INFO - Creating resource 'v1' with parent 'null'
2015-09-08 09:01:45,300 INFO - Creating resource 'videos' with parent 'v1'
2015-09-08 09:01:46,139 INFO - Creating resource '{id}' with parent 'videos'
2015-09-08 09:01:47,025 INFO - Creating resource 'metadata' with parent '{id}'
2015-09-08 09:01:47,813 INFO - Cleaning up removed resources
2015-09-08 09:01:48,035 WARN - No description found for model, will generate a unique model name
2015-09-08 09:01:48,035 INFO - Creating new model referenced from parameter: model00dea854
2015-09-08 09:01:48,035 INFO - Creating model for api id cddfwfu745 with name model00dea854
2015-09-08 09:01:48,036 ERROR - Error importing API from Swagger
java.lang.NullPointerException
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModel(ApiGatewaySdkSwaggerApiImporter.java:282)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethod$3(ApiGatewaySdkSwaggerApiImporter.java:377)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$9/1849015357.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:364)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethods(ApiGatewaySdkSwaggerApiImporter.java:348)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:111)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:107)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
ip-192-168-2-29:aws-apigateway-swagger-importer arustad (master)$
```

If I comment out the `body` parameter, I can update successfully and everything in AAG looks right (as it adds the body for me). However, since the Swagger file is missing the body now, the Swagger API documentation is incorrect. Now, if I uncomment the body and update again, the deploy to AAG succeeds and my Swagger Documentation is now correctly including the body.

Any ideas why this might be happening and how I can work around it?

Thanks!
Aaron.

**Comment by rpgreen** [comment]
Sorry for the delay. Looks like you're missing the schema for your body parameter. Request/response bodies in API Gateway require a schema.

You just need to update the body parameter like so:

```
  "name":"body",
                        "in":"body",
                        "required":true,
                        "schema": {
                            "$ref": "#/definitions/MyModel"
                        }
```

and your definitions section like so:

```
 "definitions":{
        "MyModel": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "property1": {
                    "type": "string"
                },
                "property2": {
                    "type": "string"
                }
            }
        }
    }
```

I'll beef up the validation for this case. Thanks for reporting!

**Comment by AaronRustad** [comment]
This solved my problem. I also noticed a more meaningful error message with some recent code. Thanks!
