### ISSUE TITLE
When importing to AWS I am getting error 429 too many requests.

### ISSUE THREAD

**Issue by doberloh** [awslabs/aws-apigateway-swagger-importer#33]
Maybe I am doing something wrong but here is what I have come up with after a little research.
From the docs:

Amazon API Gateway limits the rate at which you can submit requests:
You can submit a maximum of two POSTs to the applications resource per second per AWS account.
You can submit a maximum of four POSTs to an application's sessions resource per second per AWS account.

Stacktrace:

com.amazonaws.services.apigateway.model.LimitExceededException: Too Many Requests (Service: null; Status Code: 429; Error Code: null; Request ID: 01645d77-5721-11e5-b141-a1f953910c1b)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy34.putMethodResponse(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethodResponses$13(ApiGatewaySdkSwaggerApiImporter.java:729)
    at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethodResponses(ApiGatewaySdkSwaggerApiImporter.java:722)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethodResponses(ApiGatewaySdkSwaggerApiImporter.java:809)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethod(ApiGatewaySdkSwaggerApiImporter.java:583)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethods(ApiGatewaySdkSwaggerApiImporter.java:346)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:111)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:107)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)

**Comment by rpgreen** [comment]
This is a known issue. You can get around it for now by adding calls to sleep()

**Comment by doberloh** [comment]
Thanks! Ill try that.

**Comment by bholbrook73** [comment]
@rpgreen Where are you adding those calls to sleep? I'm getting this same error (which is new - it was previously working fine)

**Comment by rpgreen** [comment]
Can you send a stack trace? I don't believe any of the service limits have changed on our end. Did you recently change your swagger file? Are you using the web console at the same time?

**Comment by bholbrook73** [comment]
Yes I'm using the web console at the same time - but I'm not interacting with it - just waiting for the script to finish.

2015-09-09 14:56:41,366 INFO - Creating method parameter for api 7ld0x5ok9f and method GET with name method.request.header.authorization
2015-09-09 14:56:41,437 INFO - Creating integration with type HTTP
2015-09-09 14:56:41,688 ERROR - Error importing API from Swagger
com.amazonaws.services.apigateway.model.LimitExceededException: Too Many Requests (Service: null; Status Code: 429; Error Code: null; Request ID: a74708e3-573d-11e5-b141-a1f953910c1b)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy36.putIntegrationResponse(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createIntegrationResponses$4(ApiGatewaySdkSwaggerApiImporter.java:405)
    at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:394)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:433)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethod(ApiGatewaySdkSwaggerApiImporter.java:585)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethods(ApiGatewaySdkSwaggerApiImporter.java:346)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:111)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:107)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)

**Comment by bholbrook73** [comment]
@rpgreen  Ah... I see the sleep() that you had in there but my latest swagger is running 4+ responses types per method without a sleep being called. I added a sleep in the createMethodResponse method to ensure that large sets of method response types won't trigger the limit. I'll send you a pull request.

**Comment by rpgreen** [comment]
This should be fixed now. Please update and rebuild
