### ISSUE TITLE
API updates fail when optional basePath field is omitted.

### ISSUE THREAD

**Issue by at-nap** [awslabs/aws-apigateway-swagger-importer#44]
As per title. Setting an explicit basePath of "/" allows side-stepping the issue.

Log + stack trace:

```
2015-09-25 13:07:03,724 INFO - Cleaning up removed resources
2015-09-25 13:07:03,725 ERROR - Error importing API from Swagger
java.lang.NullPointerException
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.buildResourceSet(ApiGatewaySdkSwaggerApiImporter.java:653)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.cleanupResources(ApiGatewaySdkSwaggerApiImporter.java:637)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateResources(ApiGatewaySdkSwaggerApiImporter.java:552)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:110)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:107)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

**Comment by rpgreen** [comment]
Thanks for reporting. Fixed
