### ISSUE TITLE
BadRequestException: Resource with id 'zvhw2k' has a conflicting path

### ISSUE THREAD

**Issue by gmarchand** [awslabs/aws-apigateway-swagger-importer#49]
When trying to import, I keep getting the following error, each time.
It seems to be the same issue as #15, but the example swagger into #15 passed on my environnement.

My Swagger file seems good, I attach it in this issue

```
2015-09-30 11:00:39,602 INFO - Creating method parameter for api fdyjrcvfn1 and method PUT with name method.request.path.deviceId
2015-09-30 11:00:39,671 INFO - Creating method parameter for api fdyjrcvfn1 and method PUT with name method.request.path.userId
2015-09-30 11:00:39,739 INFO - Creating method for api id fdyjrcvfn1 and resource id 6voaif with method put
2015-09-30 11:00:40,394 INFO - Creating resource '{id}' with parent 'device'
2015-09-30 11:00:41,010 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Resource with id 'zvhw2k' has a conflicting path (Service: null; Status Code: 400; Error Code: null; Request ID: b9a10e9e-6751-11e5-8b4c-5fa58aa77440)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy30.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:158)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:316)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:255)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:93)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
2015-09-30 11:00:41,013 INFO - Deleting API fdyjrcvfn1
2015-09-30 11:00:41,486 ERROR - Error importing API from Swagger
com.amazonaws.services.apigateway.model.BadRequestException: Resource with id 'zvhw2k' has a conflicting path (Service: null; Status Code: 400; Error Code: null; Request ID: b9a10e9e-6751-11e5-8b4c-5fa58aa77440)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy30.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:158)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:316)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:255)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:93)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)

```

**Comment by gmarchand** [comment]
Swagger test file

```
{
    "swagger": "2.0",
    "info": {
        "description": "This is notification server. it uses for managed all push notifications of DED apps",
        "version": "1.0.0",
        "title": "Notification Server API",
        "contact": {
            "name": "DED Team",
            "url": "http://ded.ded",
            "email": "ded@ded.com"
        }
    },
    "host": "push.ded.com:443",
    "basePath": "/api",
    "tags": [
        {
            "name": "User",
            "description": "Operations about user"
        },
        {
            "name": "Device",
            "description": "Operations about Device"
        },
        {
            "name": "Notification",
            "description": "Operations about Push Notification"
        },
        {
            "name": "General",
            "description": "General ressources"
        }
    ],
    "schemes": [
        "https"
    ],
    "paths": {
        "/device": {
            "post": {
                "tags": [
                    "Device"
                ],
                "summary": "Create a new device",
                "description": "Create a new device",
                "operationId": "postDevice",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Device"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                }
            }
        },
        "/device/{deviceId}/user/{userId}/notification": {
            "get": {
                "tags": [
                    "Device"
                ],
                "summary": "List of notifications sent to",
                "description": "List of notifications sent to",
                "operationId": "getDeviceIdUserUserIdNotification",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "deviceId",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Notification"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Device"
                ],
                "summary": "Save new notification sent",
                "description": "Save new notification sent",
                "operationId": "postDeviceIdUserUserIdNotification",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "name": "deviceId",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Device"
                ],
                "summary": "update isOpened attribute",
                "description": "update isOpened attribute",
                "operationId": "putDeviceDeviceIdUserUserIdNotification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "deviceId",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                }
            }
        },
        "/device/{id}": {
            "put": {
                "tags": [
                    "Device"
                ],
                "summary": "Update device version, for example",
                "description": "Update device version, for example",
                "operationId": "putDeviceId",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Device"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                }
            }
        },
        "/device/{id}/user/{userId}": {
            "get": {
                "tags": [
                    "Device"
                ],
                "summary": "Get Push Info",
                "description": "Get Push Info",
                "operationId": "getDeviceIdUserUserId",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/PushInfo"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Device"
                ],
                "summary": "Associate User to a device",
                "description": "Associate User to a device",
                "operationId": "postDeviceIdUserUserId",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                }
            },
            "put": {
                "tags": [
                    "Device"
                ],
                "summary": "Update Push Info",
                "description": "Update Push Info",
                "operationId": "putDeviceIdUserUserId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/PushInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create user",
                "description": "Create user",
                "operationId": "createUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "put": {
                "tags": [
                    "User"
                ],
                "summary": "Update User profilType, for example",
                "description": "Update User profilType, for example",
                "operationId": "putUserId",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    }
                }
            }
        },
        "/user/{id}/device": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get User's device",
                "description": "Get User's device",
                "operationId": "getUserIdDevice",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Device"
                            }
                        }
                    }
                }
            }
        },
        "/user/{id}/notification": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get user's notifications",
                "description": "Get user's notifications",
                "operationId": "getUserByName",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id of user",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Notification"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "User": {
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "profilId": {
                    "type": "integer",
                    "format": "int32",
                    "description": "Used to manage family profile"
                },
                "passId": {
                    "type": "string",
                    "description": "Id P@SS"
                },
                "profilType": {
                    "type": "string"
                },
                "email": {
                    "type": "string"

                },
                "isConnected": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                },
                "isPush": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                }
            }
        },
        "Device": {
            "required": [
                "appName",
                "createdDate",
                "id",
                "updatedDate"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32",
                    "description": "DeviceToken of AWS SNS"
                },
                "appName": {
                    "type": "string",
                    "description": "Application linked to device. for example cplay or mycanal"
                },
                "appVersion": {
                    "type": "number",
                    "format": "double",
                    "description": "Application Version linked to this deviceToken"
                },
                "osVersion": {
                    "type": "string",
                    "description": "ios android win, etc..."
                },
                "deviceModel": {
                    "type": "string"
                },
                "createdDate": {
                    "type": "string",
                    "format": "date"
                },
                "updatedDate": {
                    "type": "string",
                    "format": "date"
                },
                "isConnected": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                },
                "isPush": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                }
            }
        },
        "PushInfo": {
            "required": [
                "IsPush",
                "isConnected"
            ],
            "properties": {
                "isConnected": {
                    "type": "boolean"
                },
                "IsPush": {
                    "type": "boolean"
                }
            }
        },
        "Notification": {
            "required": [
                "id",
                "notifType",
                "sendDate"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "sendDate": {
                    "type": "string",
                    "format": "date"
                },
                "notifType": {
                    "type": "string"
                },
                "contentId": {
                    "type": "string"
                },
                "isOpened": {
                    "type": "boolean",
                    "description": "TODO : Avoir la mÃ©thode PUT to update it"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}

```

**Comment by gmarchand** [comment]
OK I find the issue. The ressource statements order is important

This new version is working 

I don't know if it's a bug or not

```
{
    "swagger": "2.0",
    "info": {
        "description": "This is notification server. it uses for managed all push notifications of DED apps",
        "version": "1.0.0",
        "title": "Notification Server API",
        "contact": {
            "name": "DED Team",
            "url": "http://ded.ded",
            "email": "ded@ded.com"
        }
    },
    "host": "push.ded.com:443",
    "basePath": "/api",
    "tags": [
        {
            "name": "User",
            "description": "Operations about user"
        },
        {
            "name": "Device",
            "description": "Operations about Device"
        },
        {
            "name": "Notification",
            "description": "Operations about Push Notification"
        },
        {
            "name": "General",
            "description": "General ressources"
        }
    ],
    "schemes": [
        "https"
    ],
    "paths": {
        "/device": {
            "post": {
                "tags": [
                    "Device"
                ],
                "summary": "Create a new device",
                "description": "Create a new device",
                "operationId": "postDevice",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Device"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                }
            }
        },
        "/device/{id}": {
            "put": {
                "tags": [
                    "Device"
                ],
                "summary": "Update device version, for example",
                "description": "Update device version, for example",
                "operationId": "putDeviceId",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Device"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                }
            }
        },
        "/device/{id}/user/{userId}": {
            "get": {
                "tags": [
                    "Device"
                ],
                "summary": "Get Push Info",
                "description": "Get Push Info",
                "operationId": "getDeviceIdUserUserId",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/PushInfo"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Device"
                ],
                "summary": "Associate User to a device",
                "description": "Associate User to a device",
                "operationId": "postDeviceIdUserUserId",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                }
            },
            "put": {
                "tags": [
                    "Device"
                ],
                "summary": "Update Push Info",
                "description": "Update Push Info",
                "operationId": "putDeviceIdUserUserId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/PushInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            }
        },
        "/device/{id}/user/{userId}/notification": {
            "get": {
                "tags": [
                    "Device"
                ],
                "summary": "List of notifications sent to",
                "description": "List of notifications sent to",
                "operationId": "getDeviceIdUserUserIdNotification",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Notification"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Device"
                ],
                "summary": "Save new notification sent",
                "description": "Save new notification sent",
                "operationId": "postDeviceIdUserUserIdNotification",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "name": "deviceId",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Device"
                ],
                "summary": "update isOpened attribute",
                "description": "update isOpened attribute",
                "operationId": "putDeviceDeviceIdUserUserIdNotification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "deviceId",
                        "in": "path",
                        "description": "DeviceToken",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Notification"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create user",
                "description": "Create user",
                "operationId": "createUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "put": {
                "tags": [
                    "User"
                ],
                "summary": "Update User profilType, for example",
                "description": "Update User profilType, for example",
                "operationId": "putUserId",
                "consumes": [
                    "application/json"
                ],
                "produces": [],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success"
                    }
                }
            }
        },
        "/user/{id}/device": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get User's device",
                "description": "Get User's device",
                "operationId": "getUserIdDevice",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Device"
                            }
                        }
                    }
                }
            }
        },
        "/user/{id}/notification": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get user's notifications",
                "description": "Get user's notifications",
                "operationId": "getUserByName",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id of user",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Notification"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "User": {
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "profilId": {
                    "type": "integer",
                    "format": "int32",
                    "description": "Used to manage family profile"
                },
                "passId": {
                    "type": "string",
                    "description": "Id P@SS"
                },
                "profilType": {
                    "type": "string"
                },
                "email": {
                    "type": "string"

                },
                "isConnected": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                },
                "isPush": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                }
            }
        },
        "Device": {
            "required": [
                "appName",
                "createdDate",
                "id",
                "updatedDate"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32",
                    "description": "DeviceToken of AWS SNS"
                },
                "appName": {
                    "type": "string",
                    "description": "Application linked to device. for example cplay or mycanal"
                },
                "appVersion": {
                    "type": "number",
                    "format": "double",
                    "description": "Application Version linked to this deviceToken"
                },
                "osVersion": {
                    "type": "string",
                    "description": "ios android win, etc..."
                },
                "deviceModel": {
                    "type": "string"
                },
                "createdDate": {
                    "type": "string",
                    "format": "date"
                },
                "updatedDate": {
                    "type": "string",
                    "format": "date"
                },
                "isConnected": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                },
                "isPush": {
                    "type": "boolean",
                    "description": "Only filled when we have user and device parameters"
                }
            }
        },
        "PushInfo": {
            "required": [
                "IsPush",
                "isConnected"
            ],
            "properties": {
                "isConnected": {
                    "type": "boolean"
                },
                "IsPush": {
                    "type": "boolean"
                }
            }
        },
        "Notification": {
            "required": [
                "id",
                "notifType",
                "sendDate"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "sendDate": {
                    "type": "string",
                    "format": "date"
                },
                "notifType": {
                    "type": "string"
                },
                "contentId": {
                    "type": "string"
                },
                "isOpened": {
                    "type": "boolean",
                    "description": "TODO : Avoir la mÃ©thode PUT to update it"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by rpgreen** [comment]
This is a bug - resource order should not matter. Thanks for reporting

**Comment by EricCat** [comment]
Hi @rpgreen , what's the timeline for fix this issue? Thanks.

**Comment by opepin** [comment]
@gmarchand are you sure your issue is not you had both /device/{deviceId}/ and /device/{id}/ in the first case ? (see /device/{deviceId}/user/{userId}/notification)

AWS API gateway does not like when parameters are not name consistently.

**Comment by gmarchand** [comment]
@opepin it's working also with this change

**Comment by rpgreen** [comment]
This is working as expected. API Gateway treats /device/{deviceId} and /device/{id} as two separate conflicting resources. Tested and confirmed create/update work after changing {deviceId} to {id}
