### ISSUE TITLE
Conflicting path

### ISSUE THREAD

**Issue by koxon** [awslabs/aws-apigateway-swagger-importer#58]
Hi,

I get the following error:

```
2015-10-17 21:17:56,614 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Resource with id 'e3ns0s' has a conflicting path (Service: null; Status Code: 400; Error Code: null; Request ID: 103c2964-7536-11e5-9ae1-5d1d1101b2f0)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
```

My schemas is as follow:

```
swagger: '2.0'
info:
  version: '0.1'
  title: SA Client API
  description: API for SA Fan App and user facing website.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Sport Archive Support
    email: support@sportarchive.tv
host: sportarchive.tv
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /assets:
    get:
      description: |
        Get a list of assets in chronological order. 100 max at a time, 10 per
        default. You can limit the number of returns using 'limit' and get more
        by using the return value of 'next' from the result data of your first
        call.
      operationId: listAssets
      parameters:
        - name: limit
          in: query
          description: Limit the max number of assets returned. 100 Max. 10 Default
          required: false
          type: integer
          maximum: 100
          minimum: 1
        - name: startKey
          in: query
          description: StartKey where to start in list
          required: false
          type: string
        - name: endKey
          in: query
          description: EndKey where to stop in list
          required: false
          type: string
      responses:
        '200':
          description: list of assets
          schema:
            type: object
            items:
              $ref: '#/definitions/AssetsList'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
      x-amazon-apigateway-auth:
        type: aws_iam
      x-amazon-apigateway-integration:
        type: http
        uri: 'https://api.orchestrate.io/v0/assets'
        httpMethod: GET
        requestParameters:
          integration.request.querystring.limit: method.request.querystring.limit
          integration.request.querystring.startKey: method.request.querystring.startKey
          integration.request.querystring.endKey: method.request.querystring.endKey
        cacheNamespace: "cache namespace"
        responses:
          '200':
            statusCode: "200"
  /assets/{asset_id}:
    get:
      description: |
        Get one Asset
      operationId: getAsset
      parameters:
        - name: asset_id
          in: path
          description: ID of the item to get
          required: true
          type: string
      responses:
        '200':
          description: One asset
          schema:
            type: object
            items:
              $ref: '#/definitions/Asset'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
[...]
```

Apparently it doesn't like '/assets/{asset_id}' and says it conflicts with '/assets/'.
Any any idea why this schemas fails to validate ?

Another point, if instead of {asset_id} I put {id} (which I'd like to do), I get a different error:

```
2015-10-17 21:12:44,430 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping identifier specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 562771a0-7535-11e5-9ae1-5d1d1101b2f0)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
```

thanks for the help

**Comment by koxon** [comment]
It actually works when doing a pure create but fails when doing an update.
It also works with {id}

I guess as the path already exists it throws an error during the update but I don't think it's the wanted behavior?

**Comment by rpgreen** [comment]
This doesn't seem to behave as designed - we will look into this

**Comment by rpgreen** [comment]
@koxon Please post Swagger example with all paths

**Comment by rpgreen** [comment]
Please ensure all intermediate resources have shared parameter names.

i.e. this will cause a conflict error: 

```
/assets/{asset_id}/abc
/assets/{id}/xyz
```

it should be:

```
/assets/{asset_id}/abc
/assets/{asset_id}/xyz
```

Please reopen if you still have issues after pulling the latest code and making this change

**Comment by koxon** [comment]
Hi Ryan,

There is no intermediate resources. I confirmed that the problem is still there, unless I misunderstood what you meant.

Swagger file:

```
swagger: '2.0'
info:
  version: '0.1'
  title: SA Client API
  description: API for SA Fan App and user facing website.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Sport Archive Support
    email: support@sportarchive.tv
host: sportarchive.tv
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /assets:
    get:
      description: >
        Get a list of assets in chronological order. 100 max at a time, 10 per

        default. You can limit the number of returns using 'limit' and get more

        by using the return value of 'next' from the result data of your first

        call.
      operationId: listAssets
      parameters:
        - name: limit
          in: query
          description: Limit the max number of assets returned. 100 Max. 10 Default
          required: false
          type: integer
          maximum: 100
          minimum: 1
        - name: startKey
          in: query
          description: StartKey where to start in list
          required: false
          type: string
        - name: endKey
          in: query
          description: EndKey where to stop in list
          required: false
          type: string
      responses:
        '200':
          description: List of Assets
          schema:
            $ref: '#/definitions/AssetsList'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
      x-amazon-apigateway-auth:
        type: aws_iam
      x-amazon-apigateway-integration:
        type: http
        uri: 'https://api.orchestrate.io/v0/assets'
        httpMethod: GET
        requestParameters:
          integration.request.querystring.limit: method.request.querystring.limit
          integration.request.querystring.startKey: method.request.querystring.startKey
          integration.request.querystring.endKey: method.request.querystring.endKey
          integration.request.header.Authorization: "'Basic xxxxxxxxxx=='"
        cacheNamespace: cache namespace
        responses:
          '200':
            statusCode: '200'
  '/assets/{id}':
    get:
      description: |
        Get one Asset
      operationId: getAsset
      parameters:
        - name: id
          in: path
          description: ID of the item to get
          required: true
          type: string
      responses:
        '200':
          description: One asset
          schema:
            $ref: '#/definitions/Asset'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: http
        uri: 'https://api.orchestrate.io/v0/assets/{id}'
        httpMethod: GET
        requestParameters:
          integration.request.path.id: method.request.path.id
          integration.request.header.Authorization: "'Basic xxxxx=='"
        cacheNamespace: cache namespace
        responses:
          '200':
            statusCode: '200'
  /signin:
    post:
      description: |
        Signing the user in. Sending social info to backend.
      operationId: signin
      parameters:
        - name: user
          in: body
          description: User social info for login
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User info
          schema:
            allOf:
              - $ref: '#/definitions/Generic'
              - properties:
                  data:
                    $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws
        uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:441276146445:function:GetHelloWithName/invocations'
        credentials: 'arn:aws:iam::441276146445:role/APIGatewayLambdaExecRole'
        httpMethod: POST
        requestTemplates:
          application/json: null
        requestParameters:
        cacheNamespace: cache-namespace
        cacheKeyParameters:
        responses:
          default:
            statusCode: '200'
            responseParameters: 
            responseTemplates:
              application/json: null
  /signup:
    post:
      description: |
        Signing up a new user
      operationId: signup
      parameters:
        - name: user
          in: body
          description: User social info + new username for sign up
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User info
          schema:
            allOf:
              - $ref: '#/definitions/Generic'
              - properties:
                  data:
                    $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
  /valid_username:
    post:
      description: |
        Validate if the provided username is already used or not
      operationId: validate_username
      parameters:
        - name: username
          in: body
          description: username to check for
          required: true
          schema:
            properties:
              username:
                type: string
            required:
              - username
      responses:
        '200':
          description: Data result confirming if the username is available or not
          schema:
            allOf:
              - $ref: '#/definitions/Generic'
              - properties:
                  data:
                    type: object
                    properties:
                      available:
                        type: string
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
```

Omitted the definitions to make it shorter.

Error:

```
2015-10-19 18:16:49,595 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping identifier specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 17cfd96b-76af-11e5-a66f-ff74ec5bcc55)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy38.putIntegration(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:256)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethod(ApiGatewaySdkSwaggerApiImporter.java:411)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateMethods(ApiGatewaySdkSwaggerApiImporter.java:134)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:83)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

**Comment by rpgreen** [comment]
OK this is a different error so the original issue is resolved. 

Please make sure that all "method.request..." parameters are defined on the method level and that the parameter mapping expressions are treated as strings in YAML.

I will need the full YAML file in order to reproduce this

**Comment by koxon** [comment]
Thanks. Here is a full swagger:

```
swagger: '2.0'
info:
  version: '0.1'
  title: SA Client API
  description: API for SA Fan App and user facing website.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Sport Archive Support
    email: support@sportarchive.tv
host: sportarchive.tv
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /assets:
    get:
      description: >
        Get a list of assets in chronological order. 100 max at a time, 10 per

        default. You can limit the number of returns using 'limit' and get more

        by using the return value of 'next' from the result data of your first

        call.
      operationId: listAssets
      parameters:
        - name: limit
          in: query
          description: Limit the max number of assets returned. 100 Max. 10 Default
          required: false
          type: integer
          maximum: 100
          minimum: 1
        - name: startKey
          in: query
          description: StartKey where to start in list
          required: false
          type: string
        - name: endKey
          in: query
          description: EndKey where to stop in list
          required: false
          type: string
      responses:
        '200':
          description: List of Assets
          schema:
            $ref: '#/definitions/AssetsList'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: http
        uri: 'https://api.orchestrate.io/v0/assets'
        httpMethod: GET
        requestParameters:
          integration.request.querystring.limit: method.request.querystring.limit
          integration.request.querystring.startKey: method.request.querystring.startKey
          integration.request.querystring.endKey: method.request.querystring.endKey
          integration.request.header.Authorization: "'Basic xxxxxx=='"
        cacheNamespace: cache namespace
        responses:
          '200':
            statusCode: '200'
  '/assets/{id}':
    get:
      description: |
        Get one Asset
      operationId: getAsset
      parameters:
        - name: id
          in: path
          description: ID of the item to get
          required: true
          type: string
      responses:
        '200':
          description: One asset
          schema:
            $ref: '#/definitions/Asset'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: http
        uri: 'https://api.orchestrate.io/v0/assets/{id}'
        httpMethod: GET
        requestParameters:
          integration.request.path.id: method.request.path.id
          integration.request.header.Authorization: "'Basic xxxxx=='"
        cacheNamespace: cache namespace
        responses:
          '200':
            statusCode: '200'
  /signin:
    post:
      description: |
        Signing the user in. Sending social info to backend.
      operationId: signin
      parameters:
        - name: user
          in: body
          description: User social info for login
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User info
          schema:
            allOf:
              - $ref: '#/definitions/Generic'
              - properties:
                  data:
                    $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        type: aws
        uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:441276146445:function:GetHelloWithName/invocations'
        credentials: 'arn:aws:iam::441276146445:role/APIGatewayLambdaExecRole'
        httpMethod: POST
        requestTemplates:
          application/json: null
        requestParameters: null
        cacheNamespace: cache-namespace
        cacheKeyParameters: null
        responses:
          default:
            statusCode: '200'
            responseParameters: null
            responseTemplates:
              application/json: null
  /signup:
    post:
      description: |
        Signing up a new user
      operationId: signup
      parameters:
        - name: user
          in: body
          description: User social info + new username for sign up
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User info
          schema:
            allOf:
              - $ref: '#/definitions/Generic'
              - properties:
                  data:
                    $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
  /valid_username:
    post:
      description: |
        Validate if the provided username is already used or not
      operationId: validate_username
      parameters:
        - name: username
          in: body
          description: username to check for
          required: true
          schema:
            properties:
              username:
                type: string
            required:
              - username
      responses:
        '200':
          description: Data result confirming if the username is available or not
          schema:
            allOf:
              - $ref: '#/definitions/Generic'
              - properties:
                  data:
                    type: object
                    properties:
                      available:
                        type: string
        default:
          description: Error
          schema:
            $ref: '#/definitions/Generic'
definitions:
  User:
    type: object
    properties:
      identifier:
        type: string
      provider:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      photoURL:
        type: string
      email:
        type: string
      displayName:
        type: string
      username:
        type: string
    required:
      - email
      - identifier
      - provider
  AssetsList:
    type: object
    required:
      - count
      - results
    properties:
      count:
        type: integer
      results:
        type: object
        properties:
          path:
            type: object
            $ref: '#/definitions/Path'
          value:
            $ref: '#/definitions/Asset'
          reftime:
            type: integer
        required:
          - path
          - value
          - reftime
      next:
        type: string
  Asset:
    type: object
    properties:
      filename:
        type: string
      title:
        type: string
      description:
        type: string
      thumb_url:
        type: string
      date:
        type: string
      datetime:
        type: integer
      channel_id:
        type: string
      bucket:
        type: string
      published:
        type: boolean
      insert_time:
        type: integer
      update_time:
        type: integer
      vote_up:
        type: integer
      vote_down:
        type: integer
      encodes:
        type: object
      metadata:
        type: object
      inserted_by:
        type: string
      type:
        type: string
      encode_policy:
        type: object
      key:
        type: string
  Path:
    type: object
    properties:
      kind:
        type: string
      collection:
        type: string
      key:
        type: string
      ref:
        type: string
      reftime:
        type: integer
  Generic:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
```

Let me know if you see something weird here.

thanks
