### ISSUE TITLE
NPE importing valid Swagger 2.0

### ISSUE THREAD

**Issue by neoecos** [awslabs/aws-apigateway-swagger-importer#6]
hi,

After the issue #1, I had a new issue trying to import a valid swagger 2.0 json.

You can download and validate the swagger json here

http://online.swagger.io/validator/debug?url=https://tpaga.co/assets/swagger_engine/tpaga_api-8d343423a16b200b4af363d1841ebc1cc40d8ec2874196586142b3f953830771.json

The NPE is the following

```
 ./aws-api-import.sh -c tpaga_api-8d343423a16b200b4af363d1841ebc1cc40d8ec2874196586142b3f953830771.json 
2015-07-22 09:40:34,919 WARN - Could not load region configuration. Please ensure AWS CLI is configured via 'aws configure'. Will use default region of us-east-1
2015-07-22 09:40:35,081 INFO - Skip unsupported property name region in profile [default].
2015-07-22 09:40:35,081 INFO - Skip unsupported property name region in profile [readonly].
2015-07-22 09:40:35,081 INFO - Skip unsupported property name region in profile [tappsi].
2015-07-22 09:40:36,128 INFO - Attempting to create API from Swagger definition. Swagger file: tpaga_api-8d343423a16b200b4af363d1841ebc1cc40d8ec2874196586142b3f953830771.json
reading from tpaga_api-8d343423a16b200b4af363d1841ebc1cc40d8ec2874196586142b3f953830771.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.fasterxml.jackson.databind.node.NullNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["billingAddress"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["CreditCardCreate"])
reading from tpaga_api-8d343423a16b200b4af363d1841ebc1cc40d8ec2874196586142b3f953830771.json
com.fasterxml.jackson.databind.node.NullNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["billingAddress"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["CreditCardCreate"])
2015-07-22 09:40:36,205 ERROR - Error importing API from Swagger
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.getApiName(ApiGatewaySdkSwaggerApiImporter.java:236)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:84)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:98)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:62)
```

**Comment by neoecos** [comment]
To me, looks like a Swagger lib bug, but don't know.

**Comment by rpgreen** [comment]
This looks like an issue in swagger-parser. I would expect it to throw an exception rather than return a null Swagger object. The parser is logging some warnings related to "CreditCardCreate" and "billingAddress" models. I would recommend opening an issue with swagger-parser.
