### ISSUE TITLE
Experienced Error Resulting in ...model.BadRequestException: Invalid AWS URI

### ISSUE THREAD

**Issue by ljbrown238** [awslabs/aws-apigateway-swagger-importer#63]
I'm running the swagger.yaml file from the newbie example here: 
https://github.com/awslabs/api-gateway-secure-pet-store
I've configured everything in AWS and modified the swagger.yaml file per the instructions.

My command is this:
./aws-api-import.sh --create ~/Documents/htdocs/dev/api-gateway-secure-pet-store/src/main/resources/swagger.yaml

and I'm getting the failure below.

(First, a bunch of other INFO statements showing the /login section worked fine.  
Then it starts processing the "pets" path.)

```
2015-10-21 22:07:07,118 INFO - Creating resource 'pets' on 967xzerqi0
2015-10-21 22:07:07,241 INFO - Found input model reference NewPet
2015-10-21 22:07:07,535 INFO - Creating method response for api 7bbgttuyj4 and method POST and status 200
2015-10-21 22:07:07,583 INFO - Found reference to existing model NewPetResponse
2015-10-21 22:07:07,669 INFO - Creating method response for api 7bbgttuyj4 and method POST and status 400
2015-10-21 22:07:07,713 INFO - Found reference to existing model Error
2015-10-21 22:07:07,804 INFO - Creating method response for api 7bbgttuyj4 and method POST and status 500
2015-10-21 22:07:08,058 INFO - Found reference to existing model Error
2015-10-21 22:07:08,159 INFO - Creating integration with type AWS
2015-10-21 22:07:08,243 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid AWS URI (Service: null; Status Code: 400; Error Code: null; Request ID: bb428501-787a-11e5-921e-bd4dfcb63565)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy35.putIntegration(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:257)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:232)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:171)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$5/1636178473.accept(Unknown Source)
    at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:170)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:162)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:137)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
2015-10-21 22:07:08,245 INFO - Deleting API 7bbgttuyj4
2015-10-21 22:07:08,742 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid AWS URI (Service: null; Status Code: 400; Error Code: null; Request ID: bb428501-787a-11e5-921e-bd4dfcb63565)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
    at com.sun.proxy.$Proxy35.putIntegration(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:257)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:232)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:171)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$5/1636178473.accept(Unknown Source)
    at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:170)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:162)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:137)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

I've tried it a couple of times to rule out the 'sporadic' possibility.
Did an API change?
Any guidance would be appreciated!

**Comment by ljbrown238** [comment]
Including the CloudTrail event log in case it will help.
Thanks!

```
{
"eventVersion": "1.03",
"userIdentity": {
"type": "IAMUser",
"principalId": "xxx",
"arn": "arn:aws:iam::xxx:user/awsmgr",
"accountId": "xxx",
"accessKeyId": "xxx",
"userName": "awsmgr"
},
"eventTime": "2015-10-21T23:31:40Z",
"eventSource": "apigateway.amazonaws.com",
"eventName": "PutIntegration",
"awsRegion": "us-west-2",
"sourceIPAddress": "xxx",
"userAgent": "AmazonApiGatewaySwaggerImporter/1.0, aws-sdk-java/1.10.27 Mac_OS_X/10.10.5 Java_HotSpot(TM)_64-Bit_Server_VM/25.20-b23/1.8.0_20",
"errorCode": "BadRequestException",
"errorMessage": "Invalid AWS URI",
"requestParameters": {
"resourceId": "7y1ul1",
"httpMethod": "POST",
"putIntegrationInput": {
"httpMethod": "POST",
"type": "AWS",
"uri": "arn:was:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:xxx:function:test-function/invocations",
"requestTemplates": {
"application/json": "{\n  \"action\" : \"com.amazonaws.apigatewaydemo.action.CreatePetDemoAction\",\n  \"body\" : $input.json('$')\n}\n"
},
"credentials": "arn:aws:iam::*:user/*"
},
"restApiId": "3qykdtczx1",
"template": false
},
"responseElements": null,
"requestID": "e1b47ada-784b-11e5-921e-bd4dfcb63565",
"eventID": "a1aae508-077d-4769-a2e3-4a0c3a82f53e",
"readOnly": true,
"eventType": "AwsApiCall",
"recipientAccountId": "xxx"
}
```

**Comment by rpgreen** [comment]
Did this work previously? What is the integration uri in question? Is the
lambda function in the same account and region as the configured cli
credentials?

On Wednesday, 21 October 2015, Loren J. Brown notifications@github.com
wrote:

> Including the CloudTrail event log in case it will help.
> Thanks!
> 
> {
> "eventVersion": "1.03",
> "userIdentity": {
> "type": "IAMUser",
> "principalId": "xxx",
> "arn": "arn:aws:iam::xxx:user/awsmgr",
> "accountId": "xxx",
> "accessKeyId": "xxx",
> "userName": "awsmgr"
> },
> "eventTime": "2015-10-21T23:31:40Z",
> "eventSource": "apigateway.amazonaws.com",
> "eventName": "PutIntegration",
> "awsRegion": "us-west-2",
> "sourceIPAddress": "24.20.79.73",
> "userAgent": "AmazonApiGatewaySwaggerImporter/1.0, aws-sdk-java/1.10.27 Mac_OS_X/10.10.5 Java_HotSpot(TM)_64-Bit_Server_VM/25.20-b23/1.8.0_20",
> "errorCode": "BadRequestException",
> "errorMessage": "Invalid AWS URI",
> "requestParameters": {
> "resourceId": "7y1ul1",
> "httpMethod": "POST",
> "putIntegrationInput": {
> "httpMethod": "POST",
> "type": "AWS",
> "uri": "arn:was:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:xxx:function:test-function/invocations",
> "requestTemplates": {
> "application/json": "{\n  \"action\" : \"com.amazonaws.apigatewaydemo.action.CreatePetDemoAction\",\n  \"body\" : $input.json('$')\n}\n"
> },
> "credentials": "arn:aws:iam::_:user/_"
> },
> "restApiId": "3qykdtczx1",
> "template": false
> },
> "responseElements": null,
> "requestID": "e1b47ada-784b-11e5-921e-bd4dfcb63565",
> "eventID": "a1aae508-077d-4769-a2e3-4a0c3a82f53e",
> "readOnly": true,
> "eventType": "AwsApiCall",
> "recipientAccountId": "xxx"
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/63#issuecomment-150111967
> .

##

**Comment by ljbrown238** [comment]
It did not work previously.  It failed earlier due to an incorrect policy and I corrected it.
After that, it got as far as the /login path and then failed when half way through the /pets path.

Lambda function is in the same account and region.
I apologize, I don't know how to answer the "What is the integration URI in question.
What could I do to give you more information beyond the CloudTrail log above and the output of the failure?

**Comment by rpgreen** [comment]
There's a typo in the uri field in your yaml file - change "was" to "aws"

On Wednesday, 21 October 2015, Loren J. Brown notifications@github.com
wrote:

> It did not work previously. It failed earlier due to an incorrect policy
> and I corrected it.
> After that, it finished the /login path.
> 
> Lambda function is in the same account and region.
> I apologize, I don't know how to answer the "What is the integration URI
> in question.
> What could I do to give you more information beyond the CloudTrail log
> above and the output of the failure?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/63#issuecomment-150113282
> .

##

**Comment by ljbrown238** [comment]
Thanks for finding the doofus goofup.
And thanks to my cut/paste spell checker for jacking that up!
Appreciate the sharp eye and FAST response!!!

**Comment by ljbrown238** [comment]
Hey!  Look at it run with no errors :-)
