### ISSUE TITLE
How to Debug schemas?

### ISSUE THREAD

**Issue by sportarc** [awslabs/aws-apigateway-swagger-importer#66]
Hi guys,

My schemas is getting very long and it's becoming very hard for me to debug it.
Especially as for Swagger it is valid but not for API Gateway.

The error output coming from API Gateway is not helping at all as it doesn't reference any object, name, value, key or anything in the schemas that could help me debug it.

Am I missing something? Is there a method to debug a Schemas and pin point the issue?

For example I get this:

```
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 8dc5c631-7b8a-11e5-a101-6563b98fa5c1)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy29.createModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createModel(ApiGatewaySdkApiImporter.java:139)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModel(ApiGatewaySdkSwaggerApiImporter.java:108)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModels(ApiGatewaySdkSwaggerApiImporter.java:101)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:65)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:137)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

It doesn't help much.

Thanks

**Comment by BryanCrotaz** [comment]
I use node swagger-parser

**Comment by Shockolate** [comment]
I am getting a similar error except with RAML 0.8 and using JSON-Schema v4. I've been validating the schema here: http://www.jsonschemavalidator.net/

**Comment by sportarc** [comment]
That would require a Mock of API Gateway api I guess? The API Gateway api
barks at the inputs most often.

I usually test very often the file with swagger and then import it for
every significant change I make.
Last case scenario, I add one resource at a time and test...

When I ran into this debug problem, the issue came from having a
"description:" in and "array", like:

properties:
   attribute1:
       type: array
    \*   description: balblalal*
       items:
[...]

You cannot have a description...
Few weeks ago it was still the case not sure if it's fixed or not.

@koxon

On Thu, Dec 17, 2015 at 1:51 PM, Ted Armstrong notifications@github.com
wrote:

> I am getting a similar error except with RAML 0.8 and using JSON-Schema
> v4. I've been validating the schema here:
> http://www.jsonschemavalidator.net/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/66#issuecomment-165546095
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
ᐧ

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
