### ISSUE TITLE
Description in Array fails

### ISSUE THREAD

**Issue by sportarc** [awslabs/aws-apigateway-swagger-importer#69]
Hi,

If I have a "description" for an array properties in a model, the script fails:

```
      badges:
        description: 'Current badges selected from the achievements list. Max 3 of achievements selected'
        type: array
        items:
          $ref: '#/definitions/Achievement'
```

```
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified] (Service: null; Status Code: 400; Error Code: null; Request ID: 64d56561-7be2-11e5-b028-fb290b0e528f)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy28.createModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createModel(ApiGatewaySdkApiImporter.java:139)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModel(ApiGatewaySdkSwaggerApiImporter.java:108)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createModels(ApiGatewaySdkSwaggerApiImporter.java:101)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:65)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:137)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

Works with other properties types. Only fails with "array"

Cheers

**Comment by thedevkit** [comment]
I opened a thread in the forums: https://forums.aws.amazon.com/thread.jspa?threadID=218548

They are "aware" of the bug. Considering that the Swagger importer was working fine until last Friday (10/23), I'm guessing they released an API Gateway update that broke the validation.

**Comment by rpgreen** [comment]
Should be a fix deployed later this week

On Monday, 26 October 2015, thedevkit notifications@github.com wrote:

> This is not an issue with the Swagger importer. I opened a thread in the
> forums: https://forums.aws.amazon.com/thread.jspa?threadID=218548
> 
> They are "aware" of the bug.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/69#issuecomment-151222281
> .

##

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
