### ISSUE TITLE
Support for discriminator/polymorphism

### ISSUE THREAD

**Issue by etzlers** [awslabs/aws-apigateway-swagger-importer#74]
When using the importer I receive an error for the following definition

``` yaml
definitions:
  Location:
    type: object
    description: 'Location information.'
    discriminator: type
    properties:
      type:
        type: string
        description: 'The type of location.'
    required:
    - type
  SSID:
    type: object
    description: SSID Location.
    allOf:
    - $ref: '#/definitions/Location'
    - type: object
    properties:
      name:
        type: string
        description: Name.
    required:
    - name
  LTM:
    description: LTM Location.
    allOf: 
    - $ref: '#/definitions/Location'
    - type: object
      properties:
        version:
          type: integer
          format: int32
          description: Version.
        id:
          type: integer
          format: int32
          description: Identifier.
```

This is the error I receive when trying to import my API definitions

```
2015-11-02 15:42:20,216 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Res
ult: warnings : [], errors : [Invalid model schema specified] (Service: null; Status Code: 400; Erro
r Code: null; Request ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler
.java:117)
        at com.sun.proxy.$Proxy29.createModel(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createModel(A
piGatewaySdkApiImporter.java:139)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Model(ApiGatewaySdkSwaggerApiImporter.java:108)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Models(ApiGatewaySdkSwaggerApiImporter.java:101)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Api(ApiGatewaySdkSwaggerApiImporter.java:65)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(Ap
iGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:13
7)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
2015-11-02 15:42:20,218 INFO - Deleting API XXXXXXXXXX
2015-11-02 15:42:20,616 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.BadRequestException: Invalid model specified: Validation Res
ult: warnings : [], errors : [Invalid model schema specified] (Service: null; Status Code: 400; Erro
r Code: null; Request ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler
.java:117)
        at com.sun.proxy.$Proxy29.createModel(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.createModel(A
piGatewaySdkApiImporter.java:139)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Model(ApiGatewaySdkSwaggerApiImporter.java:108)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Models(ApiGatewaySdkSwaggerApiImporter.java:101)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.create
Api(ApiGatewaySdkSwaggerApiImporter.java:65)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(Ap
iGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:13
7)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

This error is not very descriptive but I found that if I remove the line `discriminator: type` from the Location definition that it parses through these definitions with no error.  Is polymorphism not supported or have I defined something improperly?

**Comment by rpgreen** [comment]
Swagger uses a "modified subset" of json-schema, but API Gateway requires true json-schema models. The "discriminator" field is an example of a non-standard json-schema property. There are no plans to support this at this time. For more information see https://github.com/swagger-api/swagger-spec/issues/333
