### ISSUE TITLE
Headers defined in top-level `responses` object ignored

### ISSUE THREAD

**Issue by at-nap** [awslabs/aws-apigateway-swagger-importer#83]
As per title. The following spec fails to import; note the reference to the `CORS` response object within the OPTION's responses:

``` json
{
    "swagger": "2.0",
    "info": {
        "title": "Frobnicator",
        "description": "Disappearing headers disappear.",
        "version": "0.0.0.0.1"
    },
    "schemes": [ "https" ],
    "produces": [ "application/json" ],
    "consumes": [ "application/json" ],
    "basePath": "/",
    "responses": {
        "CORS": {
            "description": "Default response for CORS method",
            "headers": {
                "Access-Control-Allow-Headers": { "type": "string" },
                "Access-Control-Allow-Methods": { "type": "string" },
                "Access-Control-Allow-Origin": { "type": "string" }
            }
        }
    },
    "paths": {
        "/frobnicate": {
            "options": {
                "responses": {
                    "200": {
                        "$ref": "#/responses/CORS"
                    }
                },
                "x-amazon-apigateway-auth" : {
                    "type" : "none"
                },
                "x-amazon-apigateway-integration" : {
                    "type" : "mock",
                    "requestTemplates": {
                        "application/json": "{ \"statusCode\" : 200 }"
                    },
                    "responses" : {
                        "default" : {
                            "statusCode" : "200",
                            "responseParameters": {
                                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'",
                                "method.response.header.Access-Control-Allow-Methods": "'*'",
                                "method.response.header.Access-Control-Allow-Origin": "'*'"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Log output:

```
ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: w
arnings : [], errors : [Invalid mapping identifier specified] (Service: null; Status Code: 400; Error Code: null; Reque
st ID: 60321afe-8d4e-11e5-ba0a-5f68352037ab)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
        at com.sun.proxy.$Proxy35.putIntegrationResponse(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createIntegrationResponses$6(ApiGatewaySdkSwaggerApiImporter.java:277)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$10/524223214.accept(Unknown Source)
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegrationResponses(ApiGatewaySdkSwaggerApiImporter.java:266)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createIntegration(ApiGatewaySdkSwaggerApiImporter.java:259)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethod(ApiGatewaySdkSwaggerApiImporter.java:232)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.lambda$createMethods$3(ApiGatewaySdkSwaggerApiImporter.java:171)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter$$Lambda$3/861623840.accept(Unknown Source)
        at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createMethods(ApiGatewaySdkSwaggerApiImporter.java:170)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:162)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:66)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:137)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

Adding the headers to the resource's responses is the obvious workaround, however, as the specification defines the same type for both reference-able top-level and method responses, I believe this shouldn't be necessary:

``` json
{
    "swagger": "2.0",
    "info": {
        "title": "Frobnicator",
        "description": "Disappearing headers disappear.",
        "version": "0.0.0.0.1"
    },
    "schemes": [ "https" ],
    "produces": [ "application/json" ],
    "consumes": [ "application/json" ],
    "basePath": "/",
    "responses": {
        "CORS": {
            "description": "Default response for CORS method",
            "headers": {
                "Access-Control-Allow-Headers": { "type": "string" },
                "Access-Control-Allow-Methods": { "type": "string" },
                "Access-Control-Allow-Origin": { "type": "string" }
            }
        }
    },
    "paths": {
        "/frobnicate": {
            "options": {
                "responses": {
                    "200": {
                        "$ref": "#/responses/CORS",
                        "headers": {
                            "Access-Control-Allow-Headers": { "type": "string" },
                            "Access-Control-Allow-Methods": { "type": "string" },
                            "Access-Control-Allow-Origin": { "type": "string" }
                        }
                    }
                },
                "x-amazon-apigateway-auth" : {
                    "type" : "none"
                },
                "x-amazon-apigateway-integration" : {
                    "type" : "mock",
                    "requestTemplates": {
                        "application/json": "{ \"statusCode\" : 200 }"
                    },
                    "responses" : {
                        "default" : {
                            "statusCode" : "200",
                            "responseParameters": {
                                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'",
                                "method.response.header.Access-Control-Allow-Methods": "'*'",
                                "method.response.header.Access-Control-Allow-Origin": "'*'"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by jackrk** [comment]
Related to https://github.com/awslabs/aws-apigateway-importer/issues/117

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
