### ISSUE TITLE
ConflictException  with sample 'petstore' 

### ISSUE THREAD

**Issue by DALDEI** [awslabs/aws-apigateway-swagger-importer#88]
Importing the sample generated from 'swagger-editor' "security" example, unchanged and saved as json.

I created the API fine, but when I tried to deploy it, get a ConflictException.
I am able to deploy the API via the AWS Console

0] [dlee@z600 aws-apigateway-importer]$ ./aws-api-import.sh --update ipuq2fnjx3 --deploy dev /home/dlee/Downloads/swagger.json
2015-11-19 20:51:13,216 INFO - Attempting to update API from Swagger definition. API identifier: ipuq2fnjx3 Swagger file: /home/dlee/Downloads/swagger.json  
reading from /home/dlee/Downloads/swagger.json  
2015-11-19 20:51:13,325 INFO - Parsed Swagger with 1 paths  
2015-11-19 20:51:13,602 INFO - Updating model for api id ipuq2fnjx3 and model name Pet  
2015-11-19 20:51:13,808 INFO - Generated json-schema for model Pet: {"type":"object","required":["name"],"properties":{"name":{"type":"string"},"tag":{"type":"string"}},"definitions":{}}  
2015-11-19 20:51:14,035 INFO - Updating model for api id ipuq2fnjx3 and model name ErrorModel
2015-11-19 20:51:14,042 INFO - Generated json-schema for model ErrorModel: {"type":"object","required":["code","message"],"properties":{"code":{"type":"integer","format":"int32"},"message":{"type":"string"}},"definitions":{}}
2015-11-19 20:51:14,291 INFO - Removing deleted model petresponse
2015-11-19 20:51:14,362 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Cannot delete model 'petresponse', is referenced in method response: /v1/pets/{id}/GET (Service: null; Status Code: 409; Error Code: null; Request ID: 2e986b44-8f29-11e5-bb65-4f55e07ff182)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.deleteResource(HalClient.java:142)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:129)
        at com.sun.proxy.$Proxy33.deleteModel(Unknown Source)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.lambda$cleanupModels$2(ApiGatewaySdkApiImporter.java:145)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter$$Lambda$3/1445424568.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.cleanupModels(ApiGatewaySdkApiImporter.java:143)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModels(ApiGatewaySdkSwaggerApiImporter.java:394)
        at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:82)
        at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
        at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)

**Comment by rpgreen** [comment]
Should be fixed now
