### ISSUE TITLE
Cannot delete model upon updating API

### ISSUE THREAD

**Issue by banzsh** [awslabs/aws-apigateway-swagger-importer#89]
I got 

```
2015-11-20 12:49:21,536 INFO - Removing deleted model modelb64d25d3
2015-11-20 12:49:21,707 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Cannot delete model 'modelb64d25d3', is referenced in method request: /v1/registration/POST (Service: null; Status Code: 409; Error Code: null; Request ID: 58bb0d5b-8f74-11e5-8f49-1b62d7abff94)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.deleteResource(HalClient.java:142)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:129)
    at com.sun.proxy.$Proxy33.deleteModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.lambda$cleanupModels$2(ApiGatewaySdkApiImporter.java:145)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.cleanupModels(ApiGatewaySdkApiImporter.java:143)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModels(ApiGatewaySdkSwaggerApiImporter.java:394)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:82)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)
```

How update can be performed if it fails on removing models? Problem occurs on `in:body` params that refer to a definition.

**Comment by banzsh** [comment]
Ignore. I had $ref's replaced by models and models themselves in #definitions thus having models created twice.
